// CodeGear C++Builder
// Copyright (c) 1995, 2022 by Embarcadero Technologies, Inc.
// All rights reserved

// (DO NOT EDIT: machine generated header) 'GLS.Generics.pas' rev: 35.00 (Windows)

#ifndef Gls_GenericsHPP
#define Gls_GenericsHPP

#pragma delphiheader begin
#pragma option push
#pragma option -w-      // All warnings off
#pragma option -Vx      // Zero-length empty class member 
#pragma pack(push,8)
#include <System.hpp>
#include <SysInit.hpp>
#include <System.SysUtils.hpp>
#include <System.Classes.hpp>
#include <System.SyncObjs.hpp>

//-- user supplied -----------------------------------------------------------

namespace Gls
{
namespace Generics
{
//-- forward type declarations -----------------------------------------------
template<typename T> class DELPHICLASS GList__1;
template<typename T> class DELPHICLASS GThreadList__1;
template<typename T> class DELPHICLASS GOrderedList__1;
template<typename T> class DELPHICLASS GStack__1;
template<typename T> class DELPHICLASS GQueue__1;
//-- type declarations -------------------------------------------------------
// Template declaration generated by Delphi parameterized types is
// used only for accessing Delphi variables and fields.
// Don't instantiate with new type parameters in user code.
template<typename T> class PASCALIMPLEMENTATION GList__1 : public System::TObject
{
	typedef System::TObject inherited;
	
	
public:
	/* [Template Alias] */
	#if defined(__clang__)
	using TListChangeEvent = void __fastcall (__closure *)(System::TObject* Sender, const T Item, System::Classes::TListNotification Action);
	#endif
	
	typedef System::DynamicArray<T> _1;
	
	
public:
	T operator[](int Index) { return this->Items[Index]; }
	
private:
	_1 FItems;
	int FCount;
	int FCapacity;
	System::Classes::TNotifyEvent FOnChange;
	
protected:
	void __fastcall SetCapacity(int Value);
	void __fastcall SetCount(int Value);
	T __fastcall GetItem(int Index);
	void __fastcall SetItem(int Index, const T Value);
	void * __fastcall GetItemAddress(int Index);
	void __fastcall Grow();
	virtual void __fastcall Notify(const T Item, System::Classes::TListNotification Action);
	
public:
	__fastcall virtual ~GList__1();
	void __fastcall Clear();
	int __fastcall Add(T AItem);
	void __fastcall Delete(int Index);
	void __fastcall Extract(T AItem);
	int __fastcall Remove(T AItem);
	int __fastcall IndexOf(T AItem);
	void __fastcall Insert(int Index, T AItem);
	void __fastcall Exchange(int Index1, int Index2);
	T __fastcall First();
	T __fastcall Last();
	__property T Items[int Index] = {read=GetItem, write=SetItem/*, default*/};
	__property void * ItemAddress[int Index] = {read=GetItemAddress};
	__property int Capacity = {read=FCapacity, write=SetCapacity, nodefault};
	__property int Count = {read=FCount, write=SetCount, nodefault};
	__property System::Classes::TNotifyEvent OnChange = {read=FOnChange, write=FOnChange};
public:
	/* TObject.Create */ inline __fastcall GList__1() : System::TObject() { }
	
};


// Template declaration generated by Delphi parameterized types is
// used only for accessing Delphi variables and fields.
// Don't instantiate with new type parameters in user code.
template<typename T> class PASCALIMPLEMENTATION GThreadList__1 : public System::TObject
{
	typedef System::TObject inherited;
	
private:
	GList__1<T>* FList;
	System::Syncobjs::TCriticalSection* FLock;
	
public:
	__fastcall GThreadList__1();
	__fastcall virtual ~GThreadList__1();
	void __fastcall Add(T AItem);
	void __fastcall Clear();
	GList__1<T>* __fastcall LockList();
	void __fastcall Remove(T AItem);
	void __fastcall UnlockList();
};


// Template declaration generated by Delphi parameterized types is
// used only for accessing Delphi variables and fields.
// Don't instantiate with new type parameters in user code.
template<typename T> class PASCALIMPLEMENTATION GOrderedList__1 : public System::TObject
{
	typedef System::TObject inherited;
	
private:
	GList__1<T>* FList;
	
protected:
	virtual void __fastcall PushItem(T AItem) = 0 ;
	virtual T __fastcall PopItem();
	virtual T __fastcall PeekItem();
	__property GList__1<T>* List = {read=FList};
	
public:
	__fastcall virtual GOrderedList__1();
	__fastcall virtual ~GOrderedList__1();
	int __fastcall Count();
	bool __fastcall AtLeast(int ACount);
	T __fastcall Push(const T AItem);
	T __fastcall Pop();
	T __fastcall Peek();
};


// Template declaration generated by Delphi parameterized types is
// used only for accessing Delphi variables and fields.
// Don't instantiate with new type parameters in user code.
template<typename T> class PASCALIMPLEMENTATION GStack__1 : public GOrderedList__1<T>
{
	typedef GOrderedList__1<T> inherited;
	
protected:
	virtual void __fastcall PushItem(T AItem);
public:
	/* {GLS_Generics}GOrderedList<GLS_Generics_GStack<T>_T>.Create */ inline __fastcall virtual GStack__1() : GOrderedList__1<T>() { }
	/* {GLS_Generics}GOrderedList<GLS_Generics_GStack<T>_T>.Destroy */ inline __fastcall virtual ~GStack__1() { }
	
};


// Template declaration generated by Delphi parameterized types is
// used only for accessing Delphi variables and fields.
// Don't instantiate with new type parameters in user code.
template<typename T> class PASCALIMPLEMENTATION GQueue__1 : public GOrderedList__1<T>
{
	typedef GOrderedList__1<T> inherited;
	
protected:
	virtual void __fastcall PushItem(T AItem);
public:
	/* {GLS_Generics}GOrderedList<GLS_Generics_GQueue<T>_T>.Create */ inline __fastcall virtual GQueue__1() : GOrderedList__1<T>() { }
	/* {GLS_Generics}GOrderedList<GLS_Generics_GQueue<T>_T>.Destroy */ inline __fastcall virtual ~GQueue__1() { }
	
};


//-- var, const, procedure ---------------------------------------------------
static const int MaxListSize = int(0x7ffffff);
}	/* namespace Generics */
}	/* namespace Gls */
#if !defined(DELPHIHEADER_NO_IMPLICIT_NAMESPACE_USE) && !defined(NO_USING_NAMESPACE_GLS_GENERICS)
using namespace Gls::Generics;
#endif
#if !defined(DELPHIHEADER_NO_IMPLICIT_NAMESPACE_USE) && !defined(NO_USING_NAMESPACE_GLS)
using namespace Gls;
#endif
#pragma pack(pop)
#pragma option pop

#pragma delphiheader end.
//-- end unit ----------------------------------------------------------------
#endif	// Gls_GenericsHPP
