// CodeGear C++Builder
// Copyright (c) 1995, 2022 by Embarcadero Technologies, Inc.
// All rights reserved

// (DO NOT EDIT: machine generated header) 'GLS.OpenGLAdapter.pas' rev: 35.00 (Windows)

#ifndef Gls_OpengladapterHPP
#define Gls_OpengladapterHPP

#pragma delphiheader begin
#pragma option push
#pragma option -w-      // All warnings off
#pragma option -Vx      // Zero-length empty class member 
#pragma pack(push,8)
#include <System.hpp>
#include <SysInit.hpp>
#include <Winapi.OpenGL.hpp>
#include <Winapi.OpenGLext.hpp>
#include <Winapi.Windows.hpp>
#include <System.SysUtils.hpp>
#include <GLS.OpenGLTokens.hpp>
#include <GLS.Strings.hpp>
#include <GLS.Logger.hpp>
#include <GLS.VectorGeometry.hpp>
#include <GLS.VectorTypes.hpp>

//-- user supplied -----------------------------------------------------------

namespace Gls
{
namespace Opengladapter
{
//-- forward type declarations -----------------------------------------------
class DELPHICLASS EOpenGLError;
class DELPHICLASS TGLExtensionsAndEntryPoints;
//-- type declarations -------------------------------------------------------
#pragma pack(push,4)
class PASCALIMPLEMENTATION EOpenGLError : public System::Sysutils::Exception
{
	typedef System::Sysutils::Exception inherited;
	
public:
	/* Exception.Create */ inline __fastcall EOpenGLError(const System::UnicodeString Msg) : System::Sysutils::Exception(Msg) { }
	/* Exception.CreateFmt */ inline __fastcall EOpenGLError(const System::UnicodeString Msg, const System::TVarRec *Args, const int Args_High) : System::Sysutils::Exception(Msg, Args, Args_High) { }
	/* Exception.CreateRes */ inline __fastcall EOpenGLError(NativeUInt Ident)/* overload */ : System::Sysutils::Exception(Ident) { }
	/* Exception.CreateRes */ inline __fastcall EOpenGLError(System::PResStringRec ResStringRec)/* overload */ : System::Sysutils::Exception(ResStringRec) { }
	/* Exception.CreateResFmt */ inline __fastcall EOpenGLError(NativeUInt Ident, const System::TVarRec *Args, const int Args_High)/* overload */ : System::Sysutils::Exception(Ident, Args, Args_High) { }
	/* Exception.CreateResFmt */ inline __fastcall EOpenGLError(System::PResStringRec ResStringRec, const System::TVarRec *Args, const int Args_High)/* overload */ : System::Sysutils::Exception(ResStringRec, Args, Args_High) { }
	/* Exception.CreateHelp */ inline __fastcall EOpenGLError(const System::UnicodeString Msg, int AHelpContext) : System::Sysutils::Exception(Msg, AHelpContext) { }
	/* Exception.CreateFmtHelp */ inline __fastcall EOpenGLError(const System::UnicodeString Msg, const System::TVarRec *Args, const int Args_High, int AHelpContext) : System::Sysutils::Exception(Msg, Args, Args_High, AHelpContext) { }
	/* Exception.CreateResHelp */ inline __fastcall EOpenGLError(NativeUInt Ident, int AHelpContext)/* overload */ : System::Sysutils::Exception(Ident, AHelpContext) { }
	/* Exception.CreateResHelp */ inline __fastcall EOpenGLError(System::PResStringRec ResStringRec, int AHelpContext)/* overload */ : System::Sysutils::Exception(ResStringRec, AHelpContext) { }
	/* Exception.CreateResFmtHelp */ inline __fastcall EOpenGLError(System::PResStringRec ResStringRec, const System::TVarRec *Args, const int Args_High, int AHelpContext)/* overload */ : System::Sysutils::Exception(ResStringRec, Args, Args_High, AHelpContext) { }
	/* Exception.CreateResFmtHelp */ inline __fastcall EOpenGLError(NativeUInt Ident, const System::TVarRec *Args, const int Args_High, int AHelpContext)/* overload */ : System::Sysutils::Exception(Ident, Args, Args_High, AHelpContext) { }
	/* Exception.Destroy */ inline __fastcall virtual ~EOpenGLError() { }
	
};

#pragma pack(pop)

#pragma pack(push,4)
class PASCALIMPLEMENTATION TGLExtensionsAndEntryPoints : public System::TObject
{
	typedef System::TObject inherited;
	
private:
	System::UnicodeString FBuffer;
	bool FInitialized;
	bool FDebug;
	unsigned FDebugIds;
	bool __fastcall CheckExtension(const System::UnicodeString Extension);
	void __fastcall ReadWGLExtensions();
	void __fastcall ReadWGLImplementationProperties();
	void * __fastcall GetAddress(const System::UnicodeString ProcName);
	void * __fastcall GetAddressNoSuffixes(const System::UnicodeString ProcName);
	void * __fastcall GetAddressAlt(const System::UnicodeString ProcName1, const System::UnicodeString ProcName2);
	void * __fastcall GetCapAddress();
	
public:
	bool VERSION_1_0;
	bool VERSION_1_1;
	bool VERSION_1_2;
	bool VERSION_1_3;
	bool VERSION_1_4;
	bool VERSION_1_5;
	bool VERSION_2_0;
	bool VERSION_2_1;
	bool VERSION_3_0;
	bool VERSION_3_1;
	bool VERSION_3_2;
	bool VERSION_3_3;
	bool VERSION_4_0;
	bool VERSION_4_1;
	bool VERSION_4_2;
	bool ARB_blend_func_extended;
	bool ARB_color_buffer_float;
	bool ARB_compatibility;
	bool ARB_copy_buffer;
	bool ARB_depth_buffer_float;
	bool ARB_depth_clamp;
	bool ARB_depth_texture;
	bool ARB_draw_buffers;
	bool ARB_draw_buffers_blend;
	bool ARB_draw_elements_base_vertex;
	bool ARB_draw_indirect;
	bool ARB_draw_instanced;
	bool ARB_explicit_attrib_location;
	bool ARB_fragment_coord_conventions;
	bool ARB_fragment_program;
	bool ARB_fragment_program_shadow;
	bool ARB_fragment_shader;
	bool ARB_framebuffer_object;
	bool ARB_framebuffer_sRGB;
	bool ARB_geometry_shader4;
	bool ARB_gpu_shader_fp64;
	bool ARB_gpu_shader5;
	bool ARB_half_float_pixel;
	bool ARB_half_float_vertex;
	bool ARB_imaging;
	bool ARB_instanced_arrays;
	bool ARB_map_buffer_range;
	bool ARB_matrix_palette;
	bool ARB_multisample;
	bool ARB_multitexture;
	bool ARB_occlusion_query;
	bool ARB_occlusion_query2;
	bool ARB_pixel_buffer_object;
	bool ARB_point_parameters;
	bool ARB_point_sprite;
	bool ARB_provoking_vertex;
	bool ARB_sample_shading;
	bool ARB_sampler_objects;
	bool ARB_seamless_cube_map;
	bool ARB_shader_bit_encoding;
	bool ARB_shader_subroutine;
	bool ARB_shader_texture_lod;
	bool ARB_shading_language_100;
	bool ARB_shadow;
	bool ARB_shadow_ambient;
	bool ARB_shader_objects;
	bool ARB_sync;
	bool ARB_tessellation_shader;
	bool ARB_texture_border_clamp;
	bool ARB_texture_buffer_object;
	bool ARB_texture_buffer_object_rgb32;
	bool ARB_texture_compression;
	bool ARB_texture_compression_rgtc;
	bool ARB_texture_cube_map;
	bool ARB_texture_cube_map_array;
	bool ARB_texture_env_add;
	bool ARB_texture_env_combine;
	bool ARB_texture_env_crossbar;
	bool ARB_texture_env_dot3;
	bool ARB_texture_float;
	bool ARB_texture_gather;
	bool ARB_texture_mirrored_repeat;
	bool ARB_texture_multisample;
	bool ARB_texture_non_power_of_two;
	bool ARB_texture_query_lod;
	bool ARB_texture_rectangle;
	bool ARB_texture_rg;
	bool ARB_texture_rgb10_a2ui;
	bool ARB_texture_swizzle;
	bool ARB_timer_query;
	bool ARB_transform_feedback2;
	bool ARB_transform_feedback3;
	bool ARB_transpose_matrix;
	bool ARB_uniform_buffer_object;
	bool ARB_vertex_array_bgra;
	bool ARB_vertex_array_object;
	bool ARB_vertex_blend;
	bool ARB_vertex_buffer_object;
	bool ARB_vertex_program;
	bool ARB_vertex_shader;
	bool ARB_vertex_type_2_10_10_10_rev;
	bool ARB_window_pos;
	bool ARB_texture_compression_bptc;
	bool ARB_get_program_binary;
	bool ARB_separate_shader_objects;
	bool ARB_shader_stencil_export;
	bool KHR_debug;
	bool ARB_clear_buffer_object;
	bool ARB_compute_shader;
	bool ARB_copy_image;
	bool ARB_debug_group;
	bool ARB_debug_label;
	bool ARB_debug_output2;
	bool ARB_ES3_compatibility;
	bool ARB_explicit_uniform_location;
	bool ARB_fragment_layer_viewport;
	bool ARB_framebuffer_no_attachments;
	bool ARB_internalformat_query2;
	bool ARB_invalidate_subdata;
	bool ARB_multi_draw_indirect;
	bool ARB_program_interface_query;
	bool ARB_shader_image_size;
	bool ARB_shader_storage_buffer_object;
	bool ARB_stencil_texturing;
	bool ARB_texture_buffer_range;
	bool ARB_texture_query_levels;
	bool ARB_texture_storage_multisample;
	bool ARB_texture_view;
	bool ARB_vertex_attrib_binding;
	bool ARB_robustness_isolation;
	bool ARB_cl_event;
	bool _3DFX_multisample;
	bool _3DFX_tbuffer;
	bool _3DFX_texture_compression_FXT1;
	bool ATI_draw_buffers;
	bool ATI_texture_compression_3dc;
	bool ATI_texture_float;
	bool ATI_texture_mirror_once;
	bool S3_s3tc;
	bool EXT_abgr;
	bool EXT_bgra;
	bool EXT_bindable_uniform;
	bool EXT_blend_color;
	bool EXT_blend_equation_separate;
	bool EXT_blend_func_separate;
	bool EXT_blend_logic_op;
	bool EXT_blend_minmax;
	bool EXT_blend_subtract;
	bool EXT_Cg_shader;
	bool EXT_clip_volume_hint;
	bool EXT_compiled_vertex_array;
	bool EXT_copy_texture;
	bool EXT_depth_bounds_test;
	bool EXT_draw_buffers2;
	bool EXT_draw_instanced;
	bool EXT_draw_range_elements;
	bool EXT_fog_coord;
	bool EXT_framebuffer_blit;
	bool EXT_framebuffer_multisample;
	bool EXT_framebuffer_object;
	bool EXT_framebuffer_sRGB;
	bool EXT_geometry_shader4;
	bool EXT_gpu_program_parameters;
	bool EXT_gpu_shader4;
	bool EXT_multi_draw_arrays;
	bool EXT_multisample;
	bool EXT_packed_depth_stencil;
	bool EXT_packed_float;
	bool EXT_packed_pixels;
	bool EXT_paletted_texture;
	bool EXT_pixel_buffer_object;
	bool EXT_polygon_offset;
	bool EXT_rescale_normal;
	bool EXT_secondary_color;
	bool EXT_separate_specular_color;
	bool EXT_shadow_funcs;
	bool EXT_shared_texture_palette;
	bool EXT_stencil_clear_tag;
	bool EXT_stencil_two_side;
	bool EXT_stencil_wrap;
	bool EXT_texture3D;
	bool EXT_texture_array;
	bool EXT_texture_buffer_object;
	bool EXT_texture_compression_latc;
	bool EXT_texture_compression_rgtc;
	bool EXT_texture_compression_s3tc;
	bool EXT_texture_cube_map;
	bool EXT_texture_edge_clamp;
	bool EXT_texture_env_add;
	bool EXT_texture_env_combine;
	bool EXT_texture_env_dot3;
	bool EXT_texture_filter_anisotropic;
	bool EXT_texture_integer;
	bool EXT_texture_lod;
	bool EXT_texture_lod_bias;
	bool EXT_texture_mirror_clamp;
	bool EXT_texture_object;
	bool EXT_texture_rectangle;
	bool EXT_texture_sRGB;
	bool EXT_texture_shared_exponent;
	bool EXT_timer_query;
	bool EXT_transform_feedback;
	bool EXT_vertex_array;
	bool EXT_texture_sRGB_decode;
	bool EXT_direct_state_access;
	bool EXT_texture_swizzle;
	bool HP_occlusion_test;
	bool IBM_rasterpos_clip;
	bool KTX_buffer_region;
	bool MESA_resize_buffers;
	bool NV_blend_square;
	bool NV_conditional_render;
	bool NV_copy_image;
	bool NV_depth_buffer_float;
	bool NV_fence;
	bool NV_float_buffer;
	bool NV_fog_distance;
	bool NV_geometry_program4;
	bool NV_light_max_exponent;
	bool NV_multisample_filter_hint;
	bool NV_occlusion_query;
	bool NV_point_sprite;
	bool NV_primitive_restart;
	bool NV_register_combiners;
	bool NV_shader_buffer_load;
	bool NV_texgen_reflection;
	bool NV_texture_compression_vtc;
	bool NV_texture_env_combine4;
	bool NV_texture_rectangle;
	bool NV_texture_shader;
	bool NV_texture_shader2;
	bool NV_texture_shader3;
	bool NV_transform_feedback;
	bool NV_vertex_array_range;
	bool NV_vertex_array_range2;
	bool NV_vertex_buffer_unified_memory;
	bool NV_vertex_program;
	bool SGI_color_matrix;
	bool SGIS_generate_mipmap;
	bool SGIS_multisample;
	bool SGIS_texture_border_clamp;
	bool SGIS_texture_color_mask;
	bool SGIS_texture_edge_clamp;
	bool SGIS_texture_lod;
	bool SGIX_depth_texture;
	bool SGIX_shadow;
	bool SGIX_shadow_ambient;
	bool AMD_vertex_shader_tessellator;
	bool WIN_swap_hint;
	bool ATI_meminfo;
	bool NVX_gpu_memory_info;
	bool NV_vdpau_interop;
	bool NV_path_rendering;
	bool GREMEDY_frame_terminator;
	bool GREMEDY_string_marker;
	bool AMDX_debug_output;
	bool ARB_debug_output;
	void __stdcall (*BindTexture)(unsigned target, unsigned texture);
	void __stdcall (*BlendFunc)(unsigned sfactor, unsigned dfactor);
	void __stdcall (*Clear)(unsigned mask);
	void __stdcall (*ClearColor)(float red, float green, float blue, float alpha);
	void __stdcall (*ClearDepth)(double depth);
	void __stdcall (*ClearStencil)(int s);
	void __stdcall (*ColorMask)(System::ByteBool red, System::ByteBool green, System::ByteBool blue, System::ByteBool alpha);
	void __stdcall (*CopyTexImage1D)(unsigned target, int level, unsigned internalFormat, int X, int y, int Width, int border);
	void __stdcall (*CopyTexImage2D)(unsigned target, int level, unsigned internalFormat, int X, int y, int Width, int Height, int border);
	void __stdcall (*CopyTexSubImage1D)(unsigned target, int level, int xoffset, int X, int y, int Width);
	void __stdcall (*CopyTexSubImage2D)(unsigned target, int level, int xoffset, int yoffset, int X, int y, int Width, int Height);
	void __stdcall (*CullFace)(unsigned mode);
	void __stdcall (*DeleteTextures)(int n, System::PCardinal textures);
	void __stdcall (*DepthFunc)(unsigned func);
	void __stdcall (*DepthMask)(System::ByteBool flag);
	void __stdcall (*DepthRange)(double zNear, double zFar);
	void __stdcall (*Disable)(unsigned cap);
	void __stdcall (*DrawArrays)(unsigned mode, int First, int Count);
	void __stdcall (*DrawBuffer)(unsigned mode);
	void __stdcall (*DrawElements)(unsigned mode, int Count, unsigned atype, void * indices);
	void __stdcall (*Enable)(unsigned cap);
	void __stdcall (*Finish)(void);
	void __stdcall (*Flush)(void);
	void __stdcall (*FrontFace)(unsigned mode);
	void __stdcall (*GenTextures)(int n, System::PCardinal textures);
	void __stdcall (*GetBooleanv)(unsigned pname, Gls::Vectortypes::PGLboolean params);
	void __stdcall (*GetDoublev)(unsigned pname, System::PDouble params);
	unsigned __stdcall (*GetError)(void);
	void __stdcall (*GetFloatv)(unsigned pname, System::PSingle params);
	void __stdcall (*GetIntegerv)(unsigned pname, System::PInteger params);
	void __stdcall (*GetPointerv)(unsigned pname, void *params);
	char * __stdcall (*GetString)(unsigned Name);
	void __stdcall (*GetTexImage)(unsigned target, int level, unsigned format, unsigned atype, void * pixels);
	void __stdcall (*GetTexLevelParameterfv)(unsigned target, int level, unsigned pname, System::PSingle params);
	void __stdcall (*GetTexLevelParameteriv)(unsigned target, int level, unsigned pname, System::PInteger params);
	void __stdcall (*GetTexParameterfv)(unsigned target, unsigned pname, System::PSingle params);
	void __stdcall (*GetTexParameteriv)(unsigned target, unsigned pname, System::PInteger params);
	void __stdcall (*Hint)(unsigned target, unsigned mode);
	System::ByteBool __stdcall (*IsEnabled)(unsigned cap);
	System::ByteBool __stdcall (*IsTexture)(unsigned texture);
	void __stdcall (*LineWidth)(float Width);
	void __stdcall (*LogicOp)(unsigned opcode);
	void __stdcall (*PixelStoref)(unsigned pname, float param);
	void __stdcall (*PixelStorei)(unsigned pname, int param);
	void __stdcall (*PointSize)(float size);
	void __stdcall (*PolygonMode)(unsigned face, unsigned mode);
	void __stdcall (*PolygonOffset)(float factor, float units);
	void __stdcall (*ReadBuffer)(unsigned mode);
	void __stdcall (*ReadPixels)(int X, int y, int Width, int Height, unsigned format, unsigned atype, void * pixels);
	void __stdcall (*Scissor)(int X, int y, int Width, int Height);
	void __stdcall (*StencilFunc)(unsigned func, int ref, unsigned mask);
	void __stdcall (*StencilMask)(unsigned mask);
	void __stdcall (*StencilOp)(unsigned fail, unsigned zfail, unsigned zpass);
	void __stdcall (*TexImage1D)(unsigned target, int level, int internalFormat, int Width, int border, unsigned format, unsigned atype, void * pixels);
	void __stdcall (*TexImage2D)(unsigned target, int level, int internalFormat, int Width, int Height, int border, unsigned format, unsigned atype, void * pixels);
	void __stdcall (*TexParameterf)(unsigned target, unsigned pname, float param);
	void __stdcall (*TexParameterfv)(unsigned target, unsigned pname, System::PSingle params);
	void __stdcall (*TexParameteri)(unsigned target, unsigned pname, int param);
	void __stdcall (*TexParameteriv)(unsigned target, unsigned pname, System::PInteger params);
	void __stdcall (*TexSubImage1D)(unsigned target, int level, int xoffset, int Width, unsigned format, unsigned atype, void * pixels);
	void __stdcall (*TexSubImage2D)(unsigned target, int level, int xoffset, int yoffset, int Width, int Height, unsigned format, unsigned atype, void * pixels);
	void __stdcall (*Viewport)(int X, int y, int Width, int Height);
	void __stdcall (*Accum)(unsigned op, float Value);
	void __stdcall (*AlphaFunc)(unsigned func, float ref);
	System::ByteBool __stdcall (*AreTexturesResident)(int n, System::PCardinal textures, Gls::Vectortypes::PGLboolean residences);
	void __stdcall (*ArrayElement)(int i);
	void __stdcall (*Begin_)(unsigned mode);
	void __stdcall (*Bitmap)(int Width, int Height, float xorig, float yorig, float xmove, float ymove, void * Bitmap);
	void __stdcall (*CallList)(unsigned list);
	void __stdcall (*CallLists)(int n, unsigned atype, void * lists);
	void __stdcall (*ClearAccum)(float red, float green, float blue, float alpha);
	void __stdcall (*ClearIndex)(float c);
	void __stdcall (*ClipPlane)(unsigned plane, System::PDouble equation);
	void __stdcall (*Color3b)(System::Int8 red, System::Int8 green, System::Int8 blue);
	void __stdcall (*Color3bv)(Gls::Vectortypes::PGLbyte v);
	void __stdcall (*Color3d)(double red, double green, double blue);
	void __stdcall (*Color3dv)(System::PDouble v);
	void __stdcall (*Color3f)(float red, float green, float blue);
	void __stdcall (*Color3fv)(System::PSingle v);
	void __stdcall (*Color3i)(int red, int green, int blue);
	void __stdcall (*Color3iv)(System::PInteger v);
	void __stdcall (*Color3s)(short red, short green, short blue);
	void __stdcall (*Color3sv)(Gls::Vectortypes::PGLshort v);
	void __stdcall (*Color3ub)(System::Byte red, System::Byte green, System::Byte blue);
	void __stdcall (*Color3ubv)(System::PByte v);
	void __stdcall (*Color3ui)(unsigned red, unsigned green, unsigned blue);
	void __stdcall (*Color3uiv)(System::PCardinal v);
	void __stdcall (*Color3us)(System::Word red, System::Word green, System::Word blue);
	void __stdcall (*Color3usv)(System::PWord v);
	void __stdcall (*Color4b)(System::Int8 red, System::Int8 green, System::Int8 blue, System::Int8 alpha);
	void __stdcall (*Color4bv)(Gls::Vectortypes::PGLbyte v);
	void __stdcall (*Color4d)(double red, double green, double blue, double alpha);
	void __stdcall (*Color4dv)(System::PDouble v);
	void __stdcall (*Color4f)(float red, float green, float blue, float alpha);
	void __stdcall (*Color4fv)(System::PSingle v);
	void __stdcall (*Color4i)(int red, int green, int blue, int alpha);
	void __stdcall (*Color4iv)(System::PInteger v);
	void __stdcall (*Color4s)(short red, short green, short blue, short alpha);
	void __stdcall (*Color4sv)(short v);
	void __stdcall (*Color4ub)(System::Byte red, System::Byte green, System::Byte blue, System::Byte alpha);
	void __stdcall (*Color4ubv)(System::PByte v);
	void __stdcall (*Color4ui)(unsigned red, unsigned green, unsigned blue, unsigned alpha);
	void __stdcall (*Color4uiv)(System::PCardinal v);
	void __stdcall (*Color4us)(System::Word red, System::Word green, System::Word blue, System::Word alpha);
	void __stdcall (*Color4usv)(System::PWord v);
	void __stdcall (*ColorMaterial)(unsigned face, unsigned mode);
	void __stdcall (*ColorPointer)(int size, unsigned atype, int stride, void * Data);
	void __stdcall (*CopyPixels)(int X, int y, int Width, int Height, unsigned atype);
	void __stdcall (*DeleteLists)(unsigned list, int range);
	void __stdcall (*DisableClientState)(unsigned aarray);
	void __stdcall (*DrawPixels)(int Width, int Height, unsigned format, unsigned atype, void * pixels);
	void __stdcall (*EdgeFlag)(System::ByteBool flag);
	void __stdcall (*EdgeFlagPointer)(int stride, void * Data);
	void __stdcall (*EdgeFlagv)(Gls::Vectortypes::PGLboolean flag);
	void __stdcall (*EnableClientState)(unsigned aarray);
	void __stdcall (*End_)(void);
	void __stdcall (*EndList)(void);
	void __stdcall (*EvalCoord1d)(double u);
	void __stdcall (*EvalCoord1dv)(System::PDouble u);
	void __stdcall (*EvalCoord1f)(float u);
	void __stdcall (*EvalCoord1fv)(System::PSingle u);
	void __stdcall (*EvalCoord2d)(double u, double v);
	void __stdcall (*EvalCoord2dv)(System::PDouble u);
	void __stdcall (*EvalCoord2f)(float u, float v);
	void __stdcall (*EvalCoord2fv)(System::PSingle u);
	void __stdcall (*EvalMesh1)(unsigned mode, int i1, int i2);
	void __stdcall (*EvalMesh2)(unsigned mode, int i1, int i2, int j1, int j2);
	void __stdcall (*EvalPoint1)(int i);
	void __stdcall (*EvalPoint2)(int i, int j);
	void __stdcall (*FeedbackBuffer)(int size, unsigned atype, System::PSingle buffer);
	void __stdcall (*Fogf)(unsigned pname, float param);
	void __stdcall (*Fogfv)(unsigned pname, System::PSingle params);
	void __stdcall (*Fogi)(unsigned pname, int param);
	void __stdcall (*Fogiv)(unsigned pname, System::PInteger params);
	void __stdcall (*Frustum)(double left, double right, double bottom, double top, double zNear, double zFar);
	unsigned __stdcall (*GenLists)(int range);
	void __stdcall (*GetClipPlane)(unsigned plane, System::PDouble equation);
	void __stdcall (*GetLightfv)(unsigned light, unsigned pname, System::PSingle params);
	void __stdcall (*GetLightiv)(unsigned light, unsigned pname, System::PInteger params);
	void __stdcall (*GetMapdv)(unsigned target, unsigned query, System::PDouble v);
	void __stdcall (*GetMapfv)(unsigned target, unsigned query, System::PSingle v);
	void __stdcall (*GetMapiv)(unsigned target, unsigned query, System::PInteger v);
	void __stdcall (*GetMaterialfv)(unsigned face, unsigned pname, System::PSingle params);
	void __stdcall (*GetMaterialiv)(unsigned face, unsigned pname, System::PInteger params);
	void __stdcall (*GetPixelMapfv)(unsigned map, System::PSingle values);
	void __stdcall (*GetPixelMapuiv)(unsigned map, System::PCardinal values);
	void __stdcall (*GetPixelMapusv)(unsigned map, System::PWord values);
	void __stdcall (*GetPolygonStipple)(System::PByte mask);
	void __stdcall (*GetTexEnvfv)(unsigned target, unsigned pname, System::PSingle params);
	void __stdcall (*GetTexEnviv)(unsigned target, unsigned pname, System::PInteger params);
	void __stdcall (*GetTexGendv)(unsigned coord, unsigned pname, System::PDouble params);
	void __stdcall (*GetTexGenfv)(unsigned coord, unsigned pname, System::PSingle params);
	void __stdcall (*GetTexGeniv)(unsigned coord, unsigned pname, System::PInteger params);
	void __stdcall (*IndexMask)(unsigned mask);
	void __stdcall (*IndexPointer)(unsigned atype, int stride, void * Data);
	void __stdcall (*Indexd)(double c);
	void __stdcall (*Indexdv)(System::PDouble c);
	void __stdcall (*Indexf)(float c);
	void __stdcall (*Indexfv)(System::PSingle c);
	void __stdcall (*Indexi)(int c);
	void __stdcall (*Indexiv)(System::PInteger c);
	void __stdcall (*Indexs)(short c);
	void __stdcall (*Indexsv)(Gls::Vectortypes::PGLshort c);
	void __stdcall (*Indexub)(System::Byte c);
	void __stdcall (*Indexubv)(System::PByte c);
	void __stdcall (*InitNames)(void);
	void __stdcall (*InterleavedArrays)(unsigned format, int stride, void * Data);
	System::ByteBool __stdcall (*IsList)(unsigned list);
	void __stdcall (*LightModelf)(unsigned pname, float param);
	void __stdcall (*LightModelfv)(unsigned pname, System::PSingle params);
	void __stdcall (*LightModeli)(unsigned pname, int param);
	void __stdcall (*LightModeliv)(unsigned pname, System::PInteger params);
	void __stdcall (*Lightf)(unsigned light, unsigned pname, float param);
	void __stdcall (*Lightfv)(unsigned light, unsigned pname, System::PSingle params);
	void __stdcall (*Lighti)(unsigned light, unsigned pname, int param);
	void __stdcall (*Lightiv)(unsigned light, unsigned pname, System::PInteger params);
	void __stdcall (*LineStipple)(int factor, System::Word pattern);
	void __stdcall (*ListBase)(unsigned base);
	void __stdcall (*LoadIdentity)(void);
	void __stdcall (*LoadMatrixd)(System::PDouble m);
	void __stdcall (*LoadMatrixf)(System::PSingle m);
	void __stdcall (*LoadName)(unsigned Name);
	void __stdcall (*Map1d)(unsigned target, double u1, double u2, int stride, int order, System::PDouble points);
	void __stdcall (*Map1f)(unsigned target, float u1, float u2, int stride, int order, System::PSingle points);
	void __stdcall (*Map2d)(unsigned target, double u1, double u2, int ustride, int uorder, double v1, double v2, int vstride, int vorder, System::PDouble points);
	void __stdcall (*Map2f)(unsigned target, float u1, float u2, int ustride, int uorder, float v1, float v2, int vstride, int vorder, System::PSingle points);
	void __stdcall (*MapGrid1d)(int un, double u1, double u2);
	void __stdcall (*MapGrid1f)(int un, float u1, float u2);
	void __stdcall (*MapGrid2d)(int un, double u1, double u2, int vn, double v1, double v2);
	void __stdcall (*MapGrid2f)(int un, float u1, float u2, int vn, float v1, float v2);
	void __stdcall (*Materialf)(unsigned face, unsigned pname, float param);
	void __stdcall (*Materialfv)(unsigned face, unsigned pname, System::PSingle params);
	void __stdcall (*Materiali)(unsigned face, unsigned pname, int param);
	void __stdcall (*Materialiv)(unsigned face, unsigned pname, System::PInteger params);
	void __stdcall (*MatrixMode)(unsigned mode);
	void __stdcall (*MultMatrixd)(System::PDouble m);
	void __stdcall (*MultMatrixf)(System::PSingle m);
	void __stdcall (*NewList)(unsigned list, unsigned mode);
	void __stdcall (*Normal3b)(System::Int8 nx, System::Int8 ny, System::Int8 nz);
	void __stdcall (*Normal3bv)(Gls::Vectortypes::PGLbyte v);
	void __stdcall (*Normal3d)(double nx, double ny, double nz);
	void __stdcall (*Normal3dv)(System::PDouble v);
	void __stdcall (*Normal3f)(float nx, float ny, float nz);
	void __stdcall (*Normal3fv)(System::PSingle v);
	void __stdcall (*Normal3i)(int nx, int ny, int nz);
	void __stdcall (*Normal3iv)(System::PInteger v);
	void __stdcall (*Normal3s)(short nx, short ny, short nz);
	void __stdcall (*Normal3sv)(Gls::Vectortypes::PGLshort v);
	void __stdcall (*NormalPointer)(unsigned atype, int stride, void * Data);
	void __stdcall (*Ortho)(double left, double right, double bottom, double top, double zNear, double zFar);
	void __stdcall (*PassThrough)(float token);
	void __stdcall (*PixelMapfv)(unsigned map, int mapsize, System::PSingle values);
	void __stdcall (*PixelMapuiv)(unsigned map, int mapsize, System::PCardinal values);
	void __stdcall (*PixelMapusv)(unsigned map, int mapsize, System::PWord values);
	void __stdcall (*PixelTransferf)(unsigned pname, float param);
	void __stdcall (*PixelTransferi)(unsigned pname, int param);
	void __stdcall (*PixelZoom)(float xfactor, float yfactor);
	void __stdcall (*PolygonStipple)(System::PByte mask);
	void __stdcall (*PopAttrib)(void);
	void __stdcall (*PopClientAttrib)(void);
	void __stdcall (*PopMatrix)(void);
	void __stdcall (*PopName)(void);
	void __stdcall (*PrioritizeTextures)(int n, System::PCardinal textures, Winapi::Windows::PSingle priorities);
	void __stdcall (*PushAttrib)(unsigned mask);
	void __stdcall (*PushClientAttrib)(unsigned mask);
	void __stdcall (*PushMatrix)(void);
	void __stdcall (*PushName)(unsigned Name);
	void __stdcall (*RasterPos2d)(double X, double y);
	void __stdcall (*RasterPos2dv)(System::PDouble v);
	void __stdcall (*RasterPos2f)(float X, float y);
	void __stdcall (*RasterPos2fv)(System::PSingle v);
	void __stdcall (*RasterPos2i)(int X, int y);
	void __stdcall (*RasterPos2iv)(System::PInteger v);
	void __stdcall (*RasterPos2s)(Gls::Vectortypes::PGLshort X, Gls::Vectortypes::PGLshort y);
	void __stdcall (*RasterPos2sv)(Gls::Vectortypes::PGLshort v);
	void __stdcall (*RasterPos3d)(double X, double y, double z);
	void __stdcall (*RasterPos3dv)(System::PDouble v);
	void __stdcall (*RasterPos3f)(float X, float y, float z);
	void __stdcall (*RasterPos3fv)(System::PSingle v);
	void __stdcall (*RasterPos3i)(int X, int y, int z);
	void __stdcall (*RasterPos3iv)(System::PInteger v);
	void __stdcall (*RasterPos3s)(short X, short y, short z);
	void __stdcall (*RasterPos3sv)(Gls::Vectortypes::PGLshort v);
	void __stdcall (*RasterPos4d)(double X, double y, double z, double w);
	void __stdcall (*RasterPos4dv)(System::PDouble v);
	void __stdcall (*RasterPos4f)(float X, float y, float z, float w);
	void __stdcall (*RasterPos4fv)(System::PSingle v);
	void __stdcall (*RasterPos4i)(int X, int y, int z, int w);
	void __stdcall (*RasterPos4iv)(System::PInteger v);
	void __stdcall (*RasterPos4s)(short X, short y, short z, short w);
	void __stdcall (*RasterPos4sv)(Gls::Vectortypes::PGLshort v);
	void __stdcall (*Rectd)(double x1, double y1, double x2, double y2);
	void __stdcall (*Rectdv)(System::PDouble v1, System::PDouble v2);
	void __stdcall (*Rectf)(float x1, float y1, float x2, float y2);
	void __stdcall (*Rectfv)(System::PSingle v1, System::PSingle v2);
	void __stdcall (*Recti)(int x1, int y1, int x2, int y2);
	void __stdcall (*Rectiv)(System::PInteger v1, System::PInteger v2);
	void __stdcall (*Rects)(short x1, short y1, short x2, short y2);
	void __stdcall (*Rectsv)(Gls::Vectortypes::PGLshort v1, Gls::Vectortypes::PGLshort v2);
	int __stdcall (*RenderMode)(unsigned mode);
	void __stdcall (*Rotated)(double ane, double X, double y, double z);
	void __stdcall (*Rotatef)(float ane, float X, float y, float z);
	void __stdcall (*Scaled)(double X, double y, double z);
	void __stdcall (*Scalef)(float X, float y, float z);
	void __stdcall (*SelectBuffer)(int size, System::PCardinal buffer);
	void __stdcall (*ShadeModel)(unsigned mode);
	void __stdcall (*TexCoord1d)(double s);
	void __stdcall (*TexCoord1dv)(System::PDouble v);
	void __stdcall (*TexCoord1f)(float s);
	void __stdcall (*TexCoord1fv)(System::PSingle v);
	void __stdcall (*TexCoord1i)(int s);
	void __stdcall (*TexCoord1iv)(System::PInteger v);
	void __stdcall (*TexCoord1s)(short s);
	void __stdcall (*TexCoord1sv)(Gls::Vectortypes::PGLshort v);
	void __stdcall (*TexCoord2d)(double s, double t);
	void __stdcall (*TexCoord2dv)(System::PDouble v);
	void __stdcall (*TexCoord2f)(float s, float t);
	void __stdcall (*TexCoord2fv)(System::PSingle v);
	void __stdcall (*TexCoord2i)(int s, int t);
	void __stdcall (*TexCoord2iv)(System::PInteger v);
	void __stdcall (*TexCoord2s)(short s, short t);
	void __stdcall (*TexCoord2sv)(Gls::Vectortypes::PGLshort v);
	void __stdcall (*TexCoord3d)(double s, double t, double r);
	void __stdcall (*TexCoord3dv)(System::PDouble v);
	void __stdcall (*TexCoord3f)(float s, float t, float r);
	void __stdcall (*TexCoord3fv)(System::PSingle v);
	void __stdcall (*TexCoord3i)(int s, int t, int r);
	void __stdcall (*TexCoord3iv)(System::PInteger v);
	void __stdcall (*TexCoord3s)(short s, short t, short r);
	void __stdcall (*TexCoord3sv)(Gls::Vectortypes::PGLshort v);
	void __stdcall (*TexCoord4d)(double s, double t, double r, double q);
	void __stdcall (*TexCoord4dv)(System::PDouble v);
	void __stdcall (*TexCoord4f)(float s, float t, float r, float q);
	void __stdcall (*TexCoord4fv)(System::PSingle v);
	void __stdcall (*TexCoord4i)(int s, int t, int r, int q);
	void __stdcall (*TexCoord4iv)(System::PInteger v);
	void __stdcall (*TexCoord4s)(short s, short t, short r, short q);
	void __stdcall (*TexCoord4sv)(Gls::Vectortypes::PGLshort v);
	void __stdcall (*TexCoordPointer)(int size, unsigned atype, int stride, void * Data);
	void __stdcall (*TexEnvf)(unsigned target, unsigned pname, float param);
	void __stdcall (*TexEnvfv)(unsigned target, unsigned pname, System::PSingle params);
	void __stdcall (*TexEnvi)(unsigned target, unsigned pname, int param);
	void __stdcall (*TexEnviv)(unsigned target, unsigned pname, System::PInteger params);
	void __stdcall (*TexGend)(unsigned coord, unsigned pname, double param);
	void __stdcall (*TexGendv)(unsigned coord, unsigned pname, System::PDouble params);
	void __stdcall (*TexGenf)(unsigned coord, unsigned pname, float param);
	void __stdcall (*TexGenfv)(unsigned coord, unsigned pname, System::PSingle params);
	void __stdcall (*TexGeni)(unsigned coord, unsigned pname, int param);
	void __stdcall (*TexGeniv)(unsigned coord, unsigned pname, System::PInteger params);
	void __stdcall (*Translated)(double X, double y, double z);
	void __stdcall (*Translatef)(float X, float y, float z);
	void __stdcall (*Vertex2d)(double X, double y);
	void __stdcall (*Vertex2dv)(System::PDouble v);
	void __stdcall (*Vertex2f)(float X, float y);
	void __stdcall (*Vertex2fv)(System::PSingle v);
	void __stdcall (*Vertex2i)(int X, int y);
	void __stdcall (*Vertex2iv)(System::PInteger v);
	void __stdcall (*Vertex2s)(short X, short y);
	void __stdcall (*Vertex2sv)(Gls::Vectortypes::PGLshort v);
	void __stdcall (*Vertex3d)(double X, double y, double z);
	void __stdcall (*Vertex3dv)(System::PDouble v);
	void __stdcall (*Vertex3f)(float X, float y, float z);
	void __stdcall (*Vertex3fv)(System::PSingle v);
	void __stdcall (*Vertex3i)(int X, int y, int z);
	void __stdcall (*Vertex3iv)(System::PInteger v);
	void __stdcall (*Vertex3s)(short X, short y, short z);
	void __stdcall (*Vertex3sv)(Gls::Vectortypes::PGLshort v);
	void __stdcall (*Vertex4d)(double X, double y, double z, double w);
	void __stdcall (*Vertex4dv)(System::PDouble v);
	void __stdcall (*Vertex4f)(float X, float y, float z, float w);
	void __stdcall (*Vertex4fv)(System::PSingle v);
	void __stdcall (*Vertex4i)(int X, int y, int z, int w);
	void __stdcall (*Vertex4iv)(System::PInteger v);
	void __stdcall (*Vertex4s)(short X, short y, short z, short w);
	void __stdcall (*Vertex4sv)(Gls::Vectortypes::PGLshort v);
	void __stdcall (*VertexPointer)(int size, unsigned atype, int stride, void * Data);
	Gls::Opengltokens::PFNGLBLENDCOLORPROC BlendColor;
	Gls::Opengltokens::PFNGLBLENDEQUATIONPROC BlendEquation;
	Gls::Opengltokens::PFNGLDRAWRANGEELEMENTSPROC DrawRangeElements;
	Gls::Opengltokens::PFNGLTEXIMAGE3DPROC TexImage3D;
	Gls::Opengltokens::PFNGLTEXSUBIMAGE3DPROC TexSubImage3D;
	Gls::Opengltokens::PFNGLCOPYTEXSUBIMAGE3DPROC CopyTexSubImage3D;
	Gls::Opengltokens::PFNGLBLENDFUNCSEPARATEPROC BlendFuncSeparate;
	Gls::Opengltokens::PFNGLMULTIDRAWARRAYSPROC MultiDrawArrays;
	Gls::Opengltokens::PFNGLMULTIDRAWELEMENTSPROC MultiDrawElements;
	Gls::Opengltokens::PFNGLPOINTPARAMETERFPROC PointParameterf;
	Gls::Opengltokens::PFNGLPOINTPARAMETERFVPROC PointParameterfv;
	Gls::Opengltokens::PFNGLPOINTPARAMETERIPROC PointParameteri;
	Gls::Opengltokens::PFNGLPOINTPARAMETERIVPROC PointParameteriv;
	Gls::Opengltokens::PFNGLBLENDEQUATIONSEPARATEPROC BlendEquationSeparate;
	Gls::Opengltokens::PFNGLDRAWBUFFERSPROC DrawBuffers;
	Gls::Opengltokens::PFNGLSTENCILOPSEPARATEPROC StencilOpSeparate;
	Gls::Opengltokens::PFNGLSTENCILFUNCSEPARATEPROC StencilFuncSeparate;
	Gls::Opengltokens::PFNGLSTENCILMASKSEPARATEPROC StencilMaskSeparate;
	Gls::Opengltokens::PFNGLLOCKARRAYSEXTPROC LockArrays;
	Gls::Opengltokens::PFNGLUNLOCKARRAYSEXTPROC UnlockArrays;
	Gls::Opengltokens::PFNGLBINDBUFFERPROC BindBuffer;
	Gls::Opengltokens::PFNGLDELETEBUFFERSPROC DeleteBuffers;
	Gls::Opengltokens::PFNGLGENBUFFERSPROC GenBuffers;
	Gls::Opengltokens::PFNGLISBUFFERPROC IsBuffer;
	Gls::Opengltokens::PFNGLBUFFERDATAPROC BufferData;
	Gls::Opengltokens::PFNGLBUFFERSUBDATAPROC BufferSubData;
	Gls::Opengltokens::PFNGLGETBUFFERSUBDATAPROC GetBufferSubData;
	Gls::Opengltokens::PFNGLMAPBUFFERPROC MapBuffer;
	Gls::Opengltokens::PFNGLUNMAPBUFFERPROC UnmapBuffer;
	Gls::Opengltokens::PFNGLGETBUFFERPARAMETERIVPROC GetBufferParameteriv;
	Gls::Opengltokens::PFNGLGETBUFFERPOINTERVPROC GetBufferPointerv;
	Gls::Opengltokens::PFNGLMAPBUFFERRANGEPROC MapBufferRange;
	Gls::Opengltokens::PFNGLFLUSHMAPPEDBUFFERRANGEPROC FlushMappedBufferRange;
	Gls::Opengltokens::PFNGLBINDBUFFERRANGEPROC BindBufferRange;
	Gls::Opengltokens::PFNGLBINDBUFFEROFFSETEXTPROC BindBufferOffset;
	Gls::Opengltokens::PFNGLBINDBUFFERBASEPROC BindBufferBase;
	Gls::Opengltokens::PFNGLTRANSFORMFEEDBACKATTRIBSNVPROC TransformFeedbackAttribs;
	Gls::Opengltokens::PFNGLTRANSFORMFEEDBACKVARYINGSNVPROC TransformFeedbackVaryingsNV;
	Gls::Opengltokens::PFNGLTRANSFORMFEEDBACKVARYINGSPROC TransformFeedbackVaryings;
	Gls::Opengltokens::PFNGLGETTRANSFORMFEEDBACKVARYINGPROC GetTransformFeedbackVarying;
	Gls::Opengltokens::PFNGLBEGINTRANSFORMFEEDBACKPROC BeginTransformFeedback;
	Gls::Opengltokens::PFNGLENDTRANSFORMFEEDBACKPROC EndTransformFeedback;
	Gls::Opengltokens::PFNGLTEXBUFFERPROC TexBuffer;
	Gls::Opengltokens::PFNGLCLEARBUFFERIVPROC ClearBufferiv;
	Gls::Opengltokens::PFNGLCLEARBUFFERUIVPROC ClearBufferuiv;
	Gls::Opengltokens::PFNGLCLEARBUFFERFVPROC ClearBufferfv;
	Gls::Opengltokens::PFNGLCLEARBUFFERFIPROC ClearBufferfi;
	Gls::Opengltokens::PFNGLGETSTRINGIPROC GetStringi;
	Gls::Opengltokens::PFNGLBINDVERTEXARRAYPROC BindVertexArray;
	Gls::Opengltokens::PFNGLDELETEVERTEXARRAYSPROC DeleteVertexArrays;
	Gls::Opengltokens::PFNGLGENVERTEXARRAYSPROC GenVertexArrays;
	Gls::Opengltokens::PFNGLISVERTEXARRAYPROC IsVertexArray;
	Gls::Opengltokens::PFNGLFLUSHVERTEXARRAYRANGENVPROC FlushVertexArrayRangeNV;
	Gls::Opengltokens::PFNGLVERTEXARRAYRANGENVPROC VertexArrayRangeNV;
	Gls::Opengltokens::PFNGLGETUNIFORMINDICESPROC GetUniformIndices;
	Gls::Opengltokens::PFNGLGETACTIVEUNIFORMSIVPROC GetActiveUniformsiv;
	Gls::Opengltokens::PFNGLGETACTIVEUNIFORMNAMEPROC GetActiveUniformName;
	Gls::Opengltokens::PFNGLGETUNIFORMBLOCKINDEXPROC GetUniformBlockIndex;
	Gls::Opengltokens::PFNGLGETACTIVEUNIFORMBLOCKIVPROC GetActiveUniformBlockiv;
	Gls::Opengltokens::PFNGLGETACTIVEUNIFORMBLOCKNAMEPROC GetActiveUniformBlockName;
	Gls::Opengltokens::PFNGLUNIFORMBLOCKBINDINGPROC UniformBlockBinding;
	Gls::Opengltokens::PFNGLCOPYBUFFERSUBDATAPROC CopyBufferSubData;
	Gls::Opengltokens::PFNGLUNIFORMBUFFEREXTPROC UniformBuffer;
	Gls::Opengltokens::PFNGLGETUNIFORMBUFFERSIZEEXTPROC GetUniformBufferSize;
	Gls::Opengltokens::PFNGLGETUNIFORMOFFSETEXTPROC GetUniformOffset;
	Gls::Opengltokens::PFNGLPRIMITIVERESTARTINDEXPROC PrimitiveRestartIndex;
	Gls::Opengltokens::PFNGLDRAWELEMENTSBASEVERTEXPROC DrawElementsBaseVertex;
	Gls::Opengltokens::PFNGLDRAWRANGEELEMENTSBASEVERTEXPROC DrawRangeElementsBaseVertex;
	Gls::Opengltokens::PFNGLDRAWELEMENTSINSTANCEDBASEVERTEXPROC DrawElementsInstancedBaseVertex;
	Gls::Opengltokens::PFNGLMULTIDRAWELEMENTSBASEVERTEXPROC MultiDrawElementsBaseVertex;
	Gls::Opengltokens::PFNGLDRAWARRAYSINSTANCEDPROC DrawArraysInstanced;
	Gls::Opengltokens::PFNGLDRAWELEMENTSINSTANCEDPROC DrawElementsInstanced;
	Gls::Opengltokens::PFNGLVERTEXATTRIB1DPROC VertexAttrib1d;
	Gls::Opengltokens::PFNGLVERTEXATTRIB1DVPROC VertexAttrib1dv;
	Gls::Opengltokens::PFNGLVERTEXATTRIB1FPROC VertexAttrib1f;
	Gls::Opengltokens::PFNGLVERTEXATTRIB1FVPROC VertexAttrib1fv;
	Gls::Opengltokens::PFNGLVERTEXATTRIB1SPROC VertexAttrib1s;
	Gls::Opengltokens::PFNGLVERTEXATTRIB1SVPROC VertexAttrib1sv;
	Gls::Opengltokens::PFNGLVERTEXATTRIB2DPROC VertexAttrib2d;
	Gls::Opengltokens::PFNGLVERTEXATTRIB2DVPROC VertexAttrib2dv;
	Gls::Opengltokens::PFNGLVERTEXATTRIB2FPROC VertexAttrib2f;
	Gls::Opengltokens::PFNGLVERTEXATTRIB2FVPROC VertexAttrib2fv;
	Gls::Opengltokens::PFNGLVERTEXATTRIB2SPROC VertexAttrib2s;
	Gls::Opengltokens::PFNGLVERTEXATTRIB2SVPROC VertexAttrib2sv;
	Gls::Opengltokens::PFNGLVERTEXATTRIB3DPROC VertexAttrib3d;
	Gls::Opengltokens::PFNGLVERTEXATTRIB3DVPROC VertexAttrib3dv;
	Gls::Opengltokens::PFNGLVERTEXATTRIB3FPROC VertexAttrib3f;
	Gls::Opengltokens::PFNGLVERTEXATTRIB3FVPROC VertexAttrib3fv;
	Gls::Opengltokens::PFNGLVERTEXATTRIB3SPROC VertexAttrib3s;
	Gls::Opengltokens::PFNGLVERTEXATTRIB3SVPROC VertexAttrib3sv;
	Gls::Opengltokens::PFNGLVERTEXATTRIB4NBVPROC VertexAttrib4Nbv;
	Gls::Opengltokens::PFNGLVERTEXATTRIB4NIVPROC VertexAttrib4Niv;
	Gls::Opengltokens::PFNGLVERTEXATTRIB4NSVPROC VertexAttrib4Nsv;
	Gls::Opengltokens::PFNGLVERTEXATTRIB4NUBPROC VertexAttrib4Nub;
	Gls::Opengltokens::PFNGLVERTEXATTRIB4NUBVPROC VertexAttrib4Nubv;
	Gls::Opengltokens::PFNGLVERTEXATTRIB4NUIVPROC VertexAttrib4Nuiv;
	Gls::Opengltokens::PFNGLVERTEXATTRIB4NUSVPROC VertexAttrib4Nusv;
	Gls::Opengltokens::PFNGLVERTEXATTRIB4BVPROC VertexAttrib4bv;
	Gls::Opengltokens::PFNGLVERTEXATTRIB4DPROC VertexAttrib4d;
	Gls::Opengltokens::PFNGLVERTEXATTRIB4DVPROC VertexAttrib4dv;
	Gls::Opengltokens::PFNGLVERTEXATTRIB4FPROC VertexAttrib4f;
	Gls::Opengltokens::PFNGLVERTEXATTRIB4FVPROC VertexAttrib4fv;
	Gls::Opengltokens::PFNGLVERTEXATTRIB4IVPROC VertexAttrib4iv;
	Gls::Opengltokens::PFNGLVERTEXATTRIB4SPROC VertexAttrib4s;
	Gls::Opengltokens::PFNGLVERTEXATTRIB4SVPROC VertexAttrib4sv;
	Gls::Opengltokens::PFNGLVERTEXATTRIB4UBVPROC VertexAttrib4ubv;
	Gls::Opengltokens::PFNGLVERTEXATTRIB4UIVPROC VertexAttrib4uiv;
	Gls::Opengltokens::PFNGLVERTEXATTRIB4USVPROC VertexAttrib4usv;
	Gls::Opengltokens::PFNGLVERTEXATTRIBPOINTERPROC VertexAttribPointer;
	Gls::Opengltokens::PFNGLVERTEXATTRIBI1IPROC VertexAttribI1i;
	Gls::Opengltokens::PFNGLVERTEXATTRIBI2IPROC VertexAttribI2i;
	Gls::Opengltokens::PFNGLVERTEXATTRIBI3IPROC VertexAttribI3i;
	Gls::Opengltokens::PFNGLVERTEXATTRIBI4IPROC VertexAttribI4i;
	Gls::Opengltokens::PFNGLVERTEXATTRIBI1UIPROC VertexAttribI1ui;
	Gls::Opengltokens::PFNGLVERTEXATTRIBI2UIPROC VertexAttribI2ui;
	Gls::Opengltokens::PFNGLVERTEXATTRIBI3UIPROC VertexAttribI3ui;
	Gls::Opengltokens::PFNGLVERTEXATTRIBI4UIPROC VertexAttribI4ui;
	Gls::Opengltokens::PFNGLVERTEXATTRIBI1IVPROC VertexAttribI1iv;
	Gls::Opengltokens::PFNGLVERTEXATTRIBI2IVPROC VertexAttribI2iv;
	Gls::Opengltokens::PFNGLVERTEXATTRIBI3IVPROC VertexAttribI3iv;
	Gls::Opengltokens::PFNGLVERTEXATTRIBI4IVPROC VertexAttribI4iv;
	Gls::Opengltokens::PFNGLVERTEXATTRIBI1UIVPROC VertexAttribI1uiv;
	Gls::Opengltokens::PFNGLVERTEXATTRIBI2UIVPROC VertexAttribI2uiv;
	Gls::Opengltokens::PFNGLVERTEXATTRIBI3UIVPROC VertexAttribI3uiv;
	Gls::Opengltokens::PFNGLVERTEXATTRIBI4UIVPROC VertexAttribI4uiv;
	Gls::Opengltokens::PFNGLVERTEXATTRIBI4BVPROC VertexAttribI4bv;
	Gls::Opengltokens::PFNGLVERTEXATTRIBI4SVPROC VertexAttribI4sv;
	Gls::Opengltokens::PFNGLVERTEXATTRIBI4UBVPROC VertexAttribI4ubv;
	Gls::Opengltokens::PFNGLVERTEXATTRIBI4USVPROC VertexAttribI4usv;
	Gls::Opengltokens::PFNGLVERTEXATTRIBIPOINTERPROC VertexAttribIPointer;
	Gls::Opengltokens::PFNGLGETVERTEXATTRIBIIVPROC GetVertexAttribIiv;
	Gls::Opengltokens::PFNGLGETVERTEXATTRIBIUIVPROC GetVertexAttribIuiv;
	Gls::Opengltokens::PFNGLUNIFORM1UIPROC Uniform1ui;
	Gls::Opengltokens::PFNGLUNIFORM2UIPROC Uniform2ui;
	Gls::Opengltokens::PFNGLUNIFORM3UIPROC Uniform3ui;
	Gls::Opengltokens::PFNGLUNIFORM4UIPROC Uniform4ui;
	Gls::Opengltokens::PFNGLUNIFORM1UIVPROC Uniform1uiv;
	Gls::Opengltokens::PFNGLUNIFORM2UIVPROC Uniform2uiv;
	Gls::Opengltokens::PFNGLUNIFORM3UIVPROC Uniform3uiv;
	Gls::Opengltokens::PFNGLUNIFORM4UIVPROC Uniform4uiv;
	Gls::Opengltokens::PFNGLGETUNIFORMUIVPROC GetUniformuiv;
	Gls::Opengltokens::PFNGLBINDFRAGDATALOCATIONPROC BindFragDataLocation;
	Gls::Opengltokens::PFNGLGETFRAGDATALOCATIONPROC GetFragDataLocation;
	Gls::Opengltokens::PFNGLCLAMPCOLORPROC ClampColor;
	Gls::Opengltokens::PFNGLCOLORMASKIPROC ColorMaski;
	Gls::Opengltokens::PFNGLGETBOOLEANI_VPROC GetBooleani_v;
	Gls::Opengltokens::PFNGLGETINTEGERI_VPROC GetIntegeri_v;
	Gls::Opengltokens::PFNGLENABLEIPROC Enablei;
	Gls::Opengltokens::PFNGLDISABLEIPROC Disablei;
	Gls::Opengltokens::PFNGLISENABLEDIPROC IsEnabledi;
	Gls::Opengltokens::PFNGLENABLEVERTEXATTRIBARRAYPROC EnableVertexAttribArray;
	Gls::Opengltokens::PFNGLDISABLEVERTEXATTRIBARRAYPROC DisableVertexAttribArray;
	Gls::Opengltokens::PFNGLVERTEXATTRIBDIVISORPROC VertexAttribDivisor;
	Gls::Opengltokens::PFNGLCLEARCOLORIIEXTPROC ClearColorIi;
	Gls::Opengltokens::PFNGLCLEARCOLORIUIEXTPROC ClearColorIui;
	Gls::Opengltokens::PFNGLTEXPARAMETERIIVPROC TexParameterIiv;
	Gls::Opengltokens::PFNGLTEXPARAMETERIUIVPROC TexParameterIuiv;
	Gls::Opengltokens::PFNGLGETTEXPARAMETERIIVPROC GetTexParameterIiv;
	Gls::Opengltokens::PFNGLGETTEXPARAMETERIUIVPROC GetTexParameterIuiv;
	Gls::Opengltokens::PFNGLPATCHPARAMETERIPROC PatchParameteri;
	Gls::Opengltokens::PFNGLPATCHPARAMETERFVPROC PatchParameterfv;
	Gls::Opengltokens::PFNGLBUFFERADDRESSRANGENVPROC BufferAddressRangeNV;
	Gls::Opengltokens::PFNGLVERTEXFORMATNVPROC VertexFormatNV;
	Gls::Opengltokens::PFNGLNORMALFORMATNVPROC NormalFormatNV;
	Gls::Opengltokens::PFNGLCOLORFORMATNVPROC ColorFormatNV;
	Gls::Opengltokens::PFNGLINDEXFORMATNVPROC IndexFormatNV;
	Gls::Opengltokens::PFNGLTEXCOORDFORMATNVPROC TexCoordFormatNV;
	Gls::Opengltokens::PFNGLEDGEFLAGFORMATNVPROC EdgeFlagFormatNV;
	Gls::Opengltokens::PFNGLSECONDARYCOLORFORMATNVPROC SecondaryColorFormatNV;
	Gls::Opengltokens::PFNGLFOGCOORDFORMATNVPROC FogCoordFormatNV;
	Gls::Opengltokens::PFNGLVERTEXATTRIBFORMATNVPROC VertexAttribFormatNV;
	Gls::Opengltokens::PFNGLVERTEXATTRIBIFORMATNVPROC VertexAttribIFormatNV;
	Gls::Opengltokens::PFNGLGETINTEGERUI64I_VNVPROC GetIntegerui64i_vNV;
	Gls::Opengltokens::PGNGLGETBUFFERPARAMETERUI64VNV GetBufferParameterui64vNV;
	Gls::Opengltokens::PFNGLMAKEBUFFERRESIDENTNVPROC MakeBufferResidentNV;
	Gls::Opengltokens::PFNGLMAKEBUFFERNONRESIDENTNVPROC MakeBufferNonResidentNV;
	Gls::Opengltokens::PFNGLISBUFFERRESIDENTNVPROC IsBufferResidentNV;
	Gls::Opengltokens::PFNGLMAKENAMEDBUFFERRESIDENTNVPROC MakeNamedBufferResidentNV;
	Gls::Opengltokens::PFNGLMAKENAMEDBUFFERNONRESIDENTNVPROC MakeNamedBufferNonResidentNV;
	Gls::Opengltokens::PFNGLISNAMEDBUFFERRESIDENTNVPROC IsNamedBufferResidentNV;
	Gls::Opengltokens::PFNGLGETNAMEDBUFFERPARAMETERUI64VNVPROC GetNamedBufferParameterui64vNV;
	Gls::Opengltokens::PFNGLGETINTEGERUI64VNVPROC GetIntegerui64vNV;
	Gls::Opengltokens::PFNGLUNIFORMUI64NVPROC Uniformui64NV;
	Gls::Opengltokens::PFNGLUNIFORMUI64VNVPROC Uniformui64vNV;
	Gls::Opengltokens::PFNGLGETUNIFORMUI64VNVPROC GetUniformui64vNV;
	Gls::Opengltokens::PFNGLPROGRAMUNIFORMUI64NVPROC ProgramUniformui64NV;
	Gls::Opengltokens::PFNGLPROGRAMUNIFORMUI64VNVPROC ProgramUniformui64vNV;
	Gls::Opengltokens::PFNGLClearBufferData ClearBufferData;
	Gls::Opengltokens::PFNGLClearBufferSubData ClearBufferSubData;
	Gls::Opengltokens::PFNGLClearNamedBufferData ClearNamedBufferData;
	Gls::Opengltokens::PFNGLClearNamedBufferSubData ClearNamedBufferSubData;
	Gls::Opengltokens::PFNGLInvalidateTexSubImage InvalidateTexSubImage;
	Gls::Opengltokens::PFNGLInvalidateTexImage InvalidateTexImage;
	Gls::Opengltokens::PFNGLInvalidateBufferSubData InvalidateBufferSubData;
	Gls::Opengltokens::PFNGLInvalidateBufferData InvalidateBufferData;
	Gls::Opengltokens::PFNGLInvalidateFramebuffer InvalidateFramebuffer;
	Gls::Opengltokens::PFNGLInvalidateSubFramebuffer InvalidateSubFramebuffer;
	Gls::Opengltokens::PFNGLMultiDrawArraysIndirect MultiDrawArraysIndirect;
	Gls::Opengltokens::PFNGLMultiDrawElementsIndirect MultiDrawElementsIndirect;
	Gls::Opengltokens::PFNGLBindVertexBuffer BindVertexBuffer;
	Gls::Opengltokens::PFNGLVertexAttribFormat VertexAttribFormat;
	Gls::Opengltokens::PFNGLVertexAttribIFormat VertexAttribIFormat;
	Gls::Opengltokens::PFNGLVertexAttribLFormat VertexAttribLFormat;
	Gls::Opengltokens::PFNGLVertexAttribBinding VertexAttribBinding;
	Gls::Opengltokens::PFNGLVertexBindingDivisor VertexBindingDivisor;
	Gls::Opengltokens::PFNGLVertexArrayBindVertexBuffer VertexArrayBindVertexBuffer;
	Gls::Opengltokens::PFNGLVertexArrayVertexAttribFormat VertexArrayVertexAttribFormat;
	Gls::Opengltokens::PFNGLVertexArrayVertexAttribIFormat VertexArrayVertexAttribIFormat;
	Gls::Opengltokens::PFNGLVertexArrayVertexAttribLFormat VertexArrayVertexAttribLFormat;
	Gls::Opengltokens::PFNGLVertexArrayVertexAttribBinding VertexArrayVertexAttribBinding;
	Gls::Opengltokens::PFNGLVertexArrayVertexBindingDivisor VertexArrayVertexBindingDivisor;
	Gls::Opengltokens::PFNGLDELETEOBJECTARBPROC DeleteObject;
	Gls::Opengltokens::PFNGLGETHANDLEARBPROC GetHandle;
	Gls::Opengltokens::PFNGLDETACHSHADERPROC DetachShader;
	Gls::Opengltokens::PFNGLCREATESHADERPROC CreateShader;
	Gls::Opengltokens::PFNGLDELETESHADERPROC DeleteShader;
	Gls::Opengltokens::PFNGLSHADERSOURCEPROC ShaderSource;
	Gls::Opengltokens::PFNGLCOMPILESHADERPROC CompileShader;
	Gls::Opengltokens::PFNGLCREATEPROGRAMPROC CreateProgram;
	Gls::Opengltokens::PFNGLDELETEPROGRAMPROC DeleteProgram;
	Gls::Opengltokens::PFNGLATTACHSHADERPROC AttachShader;
	Gls::Opengltokens::PFNGLLINKPROGRAMPROC LinkProgram;
	Gls::Opengltokens::PFNGLUSEPROGRAMPROC UseProgram;
	Gls::Opengltokens::PFNGLVALIDATEPROGRAMPROC ValidateProgram;
	Gls::Opengltokens::PFNGLUNIFORM1FPROC Uniform1f;
	Gls::Opengltokens::PFNGLUNIFORM2FPROC Uniform2f;
	Gls::Opengltokens::PFNGLUNIFORM3FPROC Uniform3f;
	Gls::Opengltokens::PFNGLUNIFORM4FPROC Uniform4f;
	Gls::Opengltokens::PFNGLUNIFORM1IPROC Uniform1i;
	Gls::Opengltokens::PFNGLUNIFORM2IPROC Uniform2i;
	Gls::Opengltokens::PFNGLUNIFORM3IPROC Uniform3i;
	Gls::Opengltokens::PFNGLUNIFORM4IPROC Uniform4i;
	Gls::Opengltokens::PFNGLUNIFORM1FVPROC Uniform1fv;
	Gls::Opengltokens::PFNGLUNIFORM2FVPROC Uniform2fv;
	Gls::Opengltokens::PFNGLUNIFORM3FVPROC Uniform3fv;
	Gls::Opengltokens::PFNGLUNIFORM4FVPROC Uniform4fv;
	Gls::Opengltokens::PFNGLUNIFORM1IVPROC Uniform1iv;
	Gls::Opengltokens::PFNGLUNIFORM2IVPROC Uniform2iv;
	Gls::Opengltokens::PFNGLUNIFORM3IVPROC Uniform3iv;
	Gls::Opengltokens::PFNGLUNIFORM4IVPROC Uniform4iv;
	Gls::Opengltokens::PFNGLUNIFORMMATRIX2FVPROC UniformMatrix2fv;
	Gls::Opengltokens::PFNGLUNIFORMMATRIX3FVPROC UniformMatrix3fv;
	Gls::Opengltokens::PFNGLUNIFORMMATRIX4FVPROC UniformMatrix4fv;
	Gls::Opengltokens::PFNGLGETOBJECTPARAMETERFVARBPROC GetObjectParameterfv;
	Gls::Opengltokens::PFNGLGETOBJECTPARAMETERIVARBPROC GetObjectParameteriv;
	Gls::Opengltokens::PFNGLGETINFOLOGARBPROC GetInfoLog;
	Gls::Opengltokens::PFNGLGETATTACHEDOBJECTSARBPROC GetAttachedObjects;
	Gls::Opengltokens::PFNGLGETACTIVEATTRIBPROC GetActiveAttrib;
	Gls::Opengltokens::PFNGLGETACTIVEUNIFORMPROC GetActiveUniform;
	Gls::Opengltokens::PFNGLGETATTACHEDSHADERSPROC GetAttachedShaders;
	Gls::Opengltokens::PFNGLGETATTRIBLOCATIONPROC GetAttribLocation;
	Gls::Opengltokens::PFNGLGETPROGRAMIVPROC GetProgramiv;
	Gls::Opengltokens::PFNGLGETPROGRAMINFOLOGPROC GetProgramInfoLog;
	Gls::Opengltokens::PFNGLGETSHADERIVPROC GetShaderiv;
	Gls::Opengltokens::PFNGLGETSHADERINFOLOGPROC GetShaderInfoLog;
	Gls::Opengltokens::PFNGLGETSHADERSOURCEPROC GetShaderSource;
	Gls::Opengltokens::PFNGLGETUNIFORMLOCATIONPROC GetUniformLocation;
	Gls::Opengltokens::PFNGLGETUNIFORMFVPROC GetUniformfv;
	Gls::Opengltokens::PFNGLGETUNIFORMIVPROC GetUniformiv;
	Gls::Opengltokens::PFNGLGETVERTEXATTRIBDVPROC GetVertexAttribdv;
	Gls::Opengltokens::PFNGLGETVERTEXATTRIBFVPROC GetVertexAttribfv;
	Gls::Opengltokens::PFNGLGETVERTEXATTRIBIVPROC GetVertexAttribiv;
	Gls::Opengltokens::PFNGLGETVERTEXATTRIBPOINTERVPROC GetVertexAttribPointerv;
	Gls::Opengltokens::PFNGLISPROGRAMPROC IsProgram;
	Gls::Opengltokens::PFNGLISSHADERPROC IsShader;
	Gls::Opengltokens::PFNGLBINDATTRIBLOCATIONPROC BindAttribLocation;
	Gls::Opengltokens::PFNGLBINDFRAGDATALOCATIONINDEXEDPROC BindFragDataLocationIndexed;
	Gls::Opengltokens::PFNGLGETFRAGDATAINDEXPROC GetFragDataIndex;
	Gls::Opengltokens::PFNGLGETVARYINGLOCATIONNVPROC GetVaryingLocation;
	Gls::Opengltokens::PFNGLGETACTIVEVARYINGNVPROC GetActiveVarying;
	Gls::Opengltokens::PFNGLACTIVEVARYINGNVPROC ActiveVarying;
	Gls::Opengltokens::PFNGLGETPROGRAMBINARYPROC GetProgramBinary;
	Gls::Opengltokens::PFNGLPROGRAMBINARYPROC ProgramBinary;
	Gls::Opengltokens::PFNGLUSEPROGRAMSTAGESPROC UseProgramStages;
	Gls::Opengltokens::PFNGLACTIVESHADERPROGRAMPROC ActiveShaderProgram;
	Gls::Opengltokens::PFNGLCREATESHADERPROGRAMVPROC CreateShaderProgramv;
	Gls::Opengltokens::PFNGLBINDPROGRAMPIPELINEPROC BindProgramPipeline;
	Gls::Opengltokens::PFNGLDELETEPROGRAMPIPELINESPROC DeleteProgramPipelines;
	Gls::Opengltokens::PFNGLGENPROGRAMPIPELINESPROC GenProgramPipelines;
	Gls::Opengltokens::PFNGLISPROGRAMPIPELINEPROC IsProgramPipeline;
	Gls::Opengltokens::PFNGLGETPROGRAMPIPELINEIVPROC GetProgramPipelineiv;
	Gls::Opengltokens::PFNGLPROGRAMUNIFORM1IPROC ProgramUniform1i;
	Gls::Opengltokens::PFNGLPROGRAMUNIFORM1IVPROC ProgramUniform1iv;
	Gls::Opengltokens::PFNGLPROGRAMUNIFORM1FPROC ProgramUniform1f;
	Gls::Opengltokens::PFNGLPROGRAMUNIFORM1FVPROC ProgramUniform1fv;
	Gls::Opengltokens::PFNGLPROGRAMUNIFORM1DPROC ProgramUniform1d;
	Gls::Opengltokens::PFNGLPROGRAMUNIFORM1DVPROC ProgramUniform1dv;
	Gls::Opengltokens::PFNGLPROGRAMUNIFORM1UIPROC ProgramUniform1ui;
	Gls::Opengltokens::PFNGLPROGRAMUNIFORM1UIVPROC ProgramUniform1uiv;
	Gls::Opengltokens::PFNGLPROGRAMUNIFORM2IPROC ProgramUniform2i;
	Gls::Opengltokens::PFNGLPROGRAMUNIFORM2IVPROC ProgramUniform2iv;
	Gls::Opengltokens::PFNGLPROGRAMUNIFORM2FPROC ProgramUniform2f;
	Gls::Opengltokens::PFNGLPROGRAMUNIFORM2FVPROC ProgramUniform2fv;
	Gls::Opengltokens::PFNGLPROGRAMUNIFORM2DPROC ProgramUniform2d;
	Gls::Opengltokens::PFNGLPROGRAMUNIFORM2DVPROC ProgramUniform2dv;
	Gls::Opengltokens::PFNGLPROGRAMUNIFORM2UIPROC ProgramUniform2ui;
	Gls::Opengltokens::PFNGLPROGRAMUNIFORM2UIVPROC ProgramUniform2uiv;
	Gls::Opengltokens::PFNGLPROGRAMUNIFORM3IPROC ProgramUniform3i;
	Gls::Opengltokens::PFNGLPROGRAMUNIFORM3IVPROC ProgramUniform3iv;
	Gls::Opengltokens::PFNGLPROGRAMUNIFORM3FPROC ProgramUniform3f;
	Gls::Opengltokens::PFNGLPROGRAMUNIFORM3FVPROC ProgramUniform3fv;
	Gls::Opengltokens::PFNGLPROGRAMUNIFORM3DPROC ProgramUniform3d;
	Gls::Opengltokens::PFNGLPROGRAMUNIFORM3DVPROC ProgramUniform3dv;
	Gls::Opengltokens::PFNGLPROGRAMUNIFORM3UIPROC ProgramUniform3ui;
	Gls::Opengltokens::PFNGLPROGRAMUNIFORM3UIVPROC ProgramUniform3uiv;
	Gls::Opengltokens::PFNGLPROGRAMUNIFORM4IPROC ProgramUniform4i;
	Gls::Opengltokens::PFNGLPROGRAMUNIFORM4IVPROC ProgramUniform4iv;
	Gls::Opengltokens::PFNGLPROGRAMUNIFORM4FPROC ProgramUniform4f;
	Gls::Opengltokens::PFNGLPROGRAMUNIFORM4FVPROC ProgramUniform4fv;
	Gls::Opengltokens::PFNGLPROGRAMUNIFORM4DPROC ProgramUniform4d;
	Gls::Opengltokens::PFNGLPROGRAMUNIFORM4DVPROC ProgramUniform4dv;
	Gls::Opengltokens::PFNGLPROGRAMUNIFORM4UIPROC ProgramUniform4ui;
	Gls::Opengltokens::PFNGLPROGRAMUNIFORM4UIVPROC ProgramUniform4uiv;
	Gls::Opengltokens::PFNGLPROGRAMUNIFORMMATRIX2FVPROC ProgramUniformMatrix2fv;
	Gls::Opengltokens::PFNGLPROGRAMUNIFORMMATRIX3FVPROC ProgramUniformMatrix3fv;
	Gls::Opengltokens::PFNGLPROGRAMUNIFORMMATRIX4FVPROC ProgramUniformMatrix4fv;
	Gls::Opengltokens::PFNGLPROGRAMUNIFORMMATRIX2DVPROC ProgramUniformMatrix2dv;
	Gls::Opengltokens::PFNGLPROGRAMUNIFORMMATRIX3DVPROC ProgramUniformMatrix3dv;
	Gls::Opengltokens::PFNGLPROGRAMUNIFORMMATRIX4DVPROC ProgramUniformMatrix4dv;
	Gls::Opengltokens::PFNGLPROGRAMUNIFORMMATRIX2X3FVPROC ProgramUniformMatrix2x3fv;
	Gls::Opengltokens::PFNGLPROGRAMUNIFORMMATRIX3X2FVPROC ProgramUniformMatrix3x2fv;
	Gls::Opengltokens::PFNGLPROGRAMUNIFORMMATRIX2X4FVPROC ProgramUniformMatrix2x4fv;
	Gls::Opengltokens::PFNGLPROGRAMUNIFORMMATRIX4X2FVPROC ProgramUniformMatrix4x2fv;
	Gls::Opengltokens::PFNGLPROGRAMUNIFORMMATRIX3X4FVPROC ProgramUniformMatrix3x4fv;
	Gls::Opengltokens::PFNGLPROGRAMUNIFORMMATRIX4X3FVPROC ProgramUniformMatrix4x3fv;
	Gls::Opengltokens::PFNGLPROGRAMUNIFORMMATRIX2X3DVPROC ProgramUniformMatrix2x3dv;
	Gls::Opengltokens::PFNGLPROGRAMUNIFORMMATRIX3X2DVPROC ProgramUniformMatrix3x2dv;
	Gls::Opengltokens::PFNGLPROGRAMUNIFORMMATRIX2X4DVPROC ProgramUniformMatrix2x4dv;
	Gls::Opengltokens::PFNGLPROGRAMUNIFORMMATRIX4X2DVPROC ProgramUniformMatrix4x2dv;
	Gls::Opengltokens::PFNGLPROGRAMUNIFORMMATRIX3X4DVPROC ProgramUniformMatrix3x4dv;
	Gls::Opengltokens::PFNGLPROGRAMUNIFORMMATRIX4X3DVPROC ProgramUniformMatrix4x3dv;
	Gls::Opengltokens::PFNGLVALIDATEPROGRAMPIPELINEPROC ValidateProgramPipeline;
	Gls::Opengltokens::PFNGLGETPROGRAMPIPELINEINFOLOGPROC GetProgramPipelineInfoLog;
	Gls::Opengltokens::PFNGLDispatchCompute DispatchCompute;
	Gls::Opengltokens::PFNGLDispatchComputeIndirect DispatchComputeIndirect;
	Gls::Opengltokens::PFNGLShaderStorageBlockBinding ShaderStorageBlockBinding;
	Gls::Opengltokens::PFNGLISRENDERBUFFERPROC IsRenderbuffer;
	Gls::Opengltokens::PFNGLBINDRENDERBUFFERPROC BindRenderbuffer;
	Gls::Opengltokens::PFNGLDELETERENDERBUFFERSPROC DeleteRenderbuffers;
	Gls::Opengltokens::PFNGLGENRENDERBUFFERSPROC GenRenderbuffers;
	Gls::Opengltokens::PFNGLRENDERBUFFERSTORAGEPROC RenderbufferStorage;
	Gls::Opengltokens::PFNGLRENDERBUFFERSTORAGEMULTISAMPLEPROC RenderbufferStorageMultisample;
	Gls::Opengltokens::PFNGLGETRENDERBUFFERPARAMETERIVPROC GetRenderbufferParameteriv;
	Gls::Opengltokens::PFNGLISFRAMEBUFFERPROC IsFramebuffer;
	Gls::Opengltokens::PFNGLBINDFRAMEBUFFERPROC BindFramebuffer;
	Gls::Opengltokens::PFNGLDELETEFRAMEBUFFERSPROC DeleteFramebuffers;
	Gls::Opengltokens::PFNGLGENFRAMEBUFFERSPROC GenFramebuffers;
	Gls::Opengltokens::PFNGLCHECKFRAMEBUFFERSTATUSPROC CheckFramebufferStatus;
	Gls::Opengltokens::PFNGLFRAMEBUFFERTEXTUREPROC FramebufferTexture;
	Gls::Opengltokens::PFNGLFRAMEBUFFERTEXTURE1DPROC FramebufferTexture1D;
	Gls::Opengltokens::PFNGLFRAMEBUFFERTEXTURE2DPROC FramebufferTexture2D;
	Gls::Opengltokens::PFNGLFRAMEBUFFERTEXTURE3DPROC FramebufferTexture3D;
	Gls::Opengltokens::PFNGLFRAMEBUFFERTEXTURELAYERPROC FramebufferTextureLayer;
	Gls::Opengltokens::PFNGLFRAMEBUFFERTEXTUREFACEARBPROC FramebufferTextureFace;
	Gls::Opengltokens::PFNGLFRAMEBUFFERRENDERBUFFERPROC FramebufferRenderbuffer;
	Gls::Opengltokens::PFNGLGETFRAMEBUFFERATTACHMENTPARAMETERIVPROC GetFramebufferAttachmentParameteriv;
	Gls::Opengltokens::PFNGLBLITFRAMEBUFFERPROC BlitFramebuffer;
	Gls::Opengltokens::PFNGLGENERATEMIPMAPPROC GenerateMipmap;
	Gls::Opengltokens::PFNGLFramebufferParameteri FramebufferParameteri;
	Gls::Opengltokens::PFNGLNamedFramebufferParameteri NamedFramebufferParameteri;
	Gls::Opengltokens::PFNGLGetNamedFramebufferParameteriv GetNamedFramebufferParameteriv;
	Gls::Opengltokens::PFNGLGENQUERIESPROC GenQueries;
	Gls::Opengltokens::PFNGLDELETEQUERIESPROC DeleteQueries;
	Gls::Opengltokens::PFNGLISQUERYPROC IsQuery;
	Gls::Opengltokens::PFNGLBEGINQUERYPROC BeginQuery;
	Gls::Opengltokens::PFNGLENDQUERYPROC EndQuery;
	Gls::Opengltokens::PFNGLGETQUERYIVPROC GetQueryiv;
	Gls::Opengltokens::PFNGLGETQUERYOBJECTIVPROC GetQueryObjectiv;
	Gls::Opengltokens::PFNGLGETQUERYOBJECTUIVPROC GetQueryObjectuiv;
	Gls::Opengltokens::PFNGLQUERYCOUNTERPROC QueryCounter;
	Gls::Opengltokens::PFNGLGETQUERYOBJECTI64VPROC GetQueryObjecti64v;
	Gls::Opengltokens::PFNGLGETQUERYOBJECTUI64VPROC GetQueryObjectui64v;
	Gls::Opengltokens::PFNGLGetInternalformati64v GetInternalformati64v;
	Gls::Opengltokens::PFNGLGetProgramInterfaceiv GetProgramInterfaceiv;
	Gls::Opengltokens::PFNGLGetProgramResourceIndex GetProgramResourceIndex;
	Gls::Opengltokens::PFNGLGetProgramResourceName GetProgramResourceName;
	Gls::Opengltokens::PFNGLGetProgramResourceiv GetProgramResourceiv;
	Gls::Opengltokens::PFNGLGetProgramResourceLocation GetProgramResourceLocation;
	Gls::Opengltokens::PFNGLGetProgramResourceLocationIndex GetProgramResourceLocationIndex;
	Gls::Opengltokens::PFNGLACTIVETEXTUREPROC ActiveTexture;
	Gls::Opengltokens::PFNGLSAMPLECOVERAGEPROC SampleCoverage;
	Gls::Opengltokens::PFNGLCOMPRESSEDTEXIMAGE3DPROC CompressedTexImage3D;
	Gls::Opengltokens::PFNGLCOMPRESSEDTEXIMAGE2DPROC CompressedTexImage2D;
	Gls::Opengltokens::PFNGLCOMPRESSEDTEXIMAGE1DPROC CompressedTexImage1D;
	Gls::Opengltokens::PFNGLCOMPRESSEDTEXSUBIMAGE3DPROC CompressedTexSubImage3D;
	Gls::Opengltokens::PFNGLCOMPRESSEDTEXSUBIMAGE2DPROC CompressedTexSubImage2D;
	Gls::Opengltokens::PFNGLCOMPRESSEDTEXSUBIMAGE1DPROC CompressedTexSubImage1D;
	Gls::Opengltokens::PFNGLGETCOMPRESSEDTEXIMAGEPROC GetCompressedTexImage;
	Gls::Opengltokens::PFNGLCLIENTACTIVETEXTUREPROC ClientActiveTexture;
	Gls::Opengltokens::PFNGLMULTITEXCOORD1DPROC MultiTexCoord1d;
	Gls::Opengltokens::PFNGLMULTITEXCOORD1DVPROC MultiTexCoord1dV;
	Gls::Opengltokens::PFNGLMULTITEXCOORD1FPROC MultiTexCoord1f;
	Gls::Opengltokens::PFNGLMULTITEXCOORD1FVPROC MultiTexCoord1fv;
	Gls::Opengltokens::PFNGLMULTITEXCOORD1IPROC MultiTexCoord1i;
	Gls::Opengltokens::PFNGLMULTITEXCOORD1IVPROC MultiTexCoord1iv;
	Gls::Opengltokens::PFNGLMULTITEXCOORD1SPROC MultiTexCoord1s;
	Gls::Opengltokens::PFNGLMULTITEXCOORD1SVPROC MultiTexCoord1sv;
	Gls::Opengltokens::PFNGLMULTITEXCOORD2DPROC MultiTexCoord2d;
	Gls::Opengltokens::PFNGLMULTITEXCOORD2DVPROC MultiTexCoord2dv;
	Gls::Opengltokens::PFNGLMULTITEXCOORD2FPROC MultiTexCoord2f;
	Gls::Opengltokens::PFNGLMULTITEXCOORD2FVPROC MultiTexCoord2fv;
	Gls::Opengltokens::PFNGLMULTITEXCOORD2IPROC MultiTexCoord2i;
	Gls::Opengltokens::PFNGLMULTITEXCOORD2IVPROC MultiTexCoord2iv;
	Gls::Opengltokens::PFNGLMULTITEXCOORD2SPROC MultiTexCoord2s;
	Gls::Opengltokens::PFNGLMULTITEXCOORD2SVPROC MultiTexCoord2sv;
	Gls::Opengltokens::PFNGLMULTITEXCOORD3DPROC MultiTexCoord3d;
	Gls::Opengltokens::PFNGLMULTITEXCOORD3DVPROC MultiTexCoord3dv;
	Gls::Opengltokens::PFNGLMULTITEXCOORD3FPROC MultiTexCoord3f;
	Gls::Opengltokens::PFNGLMULTITEXCOORD3FVPROC MultiTexCoord3fv;
	Gls::Opengltokens::PFNGLMULTITEXCOORD3IPROC MultiTexCoord3i;
	Gls::Opengltokens::PFNGLMULTITEXCOORD3IVPROC MultiTexCoord3iv;
	Gls::Opengltokens::PFNGLMULTITEXCOORD3SPROC MultiTexCoord3s;
	Gls::Opengltokens::PFNGLMULTITEXCOORD3SVPROC MultiTexCoord3sv;
	Gls::Opengltokens::PFNGLMULTITEXCOORD4DPROC MultiTexCoord4d;
	Gls::Opengltokens::PFNGLMULTITEXCOORD4DVPROC MultiTexCoord4dv;
	Gls::Opengltokens::PFNGLMULTITEXCOORD4FPROC MultiTexCoord4f;
	Gls::Opengltokens::PFNGLMULTITEXCOORD4FVPROC MultiTexCoord4fv;
	Gls::Opengltokens::PFNGLMULTITEXCOORD4IPROC MultiTexCoord4i;
	Gls::Opengltokens::PFNGLMULTITEXCOORD4IVPROC MultiTexCoord4iv;
	Gls::Opengltokens::PFNGLMULTITEXCOORD4SPROC MultiTexCoord4s;
	Gls::Opengltokens::PFNGLMULTITEXCOORD4SVPROC MultiTexCoord4sv;
	Gls::Opengltokens::PFNGLGETINTEGER64I_VPROC GetInteger64i_v;
	Gls::Opengltokens::PFNGLGETBUFFERPARAMETERI64VPROC GetBufferParameteri64v;
	Gls::Opengltokens::PFNGLPROGRAMPARAMETERIPROC ProgramParameteri;
	Gls::Opengltokens::PFNGLPROGRAMSTRINGARBPROC ProgramString;
	Gls::Opengltokens::PFNGLBINDPROGRAMARBPROC BindProgram;
	Gls::Opengltokens::PFNGLDELETEPROGRAMSARBPROC DeletePrograms;
	Gls::Opengltokens::PFNGLGENPROGRAMSARBPROC GenPrograms;
	Gls::Opengltokens::PFNGLPROGRAMENVPARAMETER4DARBPROC ProgramEnvParameter4d;
	Gls::Opengltokens::PFNGLPROGRAMENVPARAMETER4DVARBPROC ProgramEnvParameter4dv;
	Gls::Opengltokens::PFNGLPROGRAMENVPARAMETER4FARBPROC ProgramEnvParameter4f;
	Gls::Opengltokens::PFNGLPROGRAMENVPARAMETER4FVARBPROC ProgramEnvParameter4fv;
	Gls::Opengltokens::PFNGLPROGRAMLOCALPARAMETER4DARBPROC ProgramLocalParameter4d;
	Gls::Opengltokens::PFNGLPROGRAMLOCALPARAMETER4DVARBPROC ProgramLocalParameter4dv;
	Gls::Opengltokens::PFNGLPROGRAMLOCALPARAMETER4FARBPROC ProgramLocalParameter4f;
	Gls::Opengltokens::PFNGLPROGRAMLOCALPARAMETER4FVARBPROC ProgramLocalParameter4fv;
	Gls::Opengltokens::PFNGLGETPROGRAMENVPARAMETERDVARBPROC GetProgramEnvParameterdv;
	Gls::Opengltokens::PFNGLGETPROGRAMENVPARAMETERFVARBPROC GetProgramEnvParameterfv;
	Gls::Opengltokens::PFNGLGETPROGRAMLOCALPARAMETERDVARBPROC GetProgramLocalParameterdv;
	Gls::Opengltokens::PFNGLGETPROGRAMLOCALPARAMETERFVARBPROC GetProgramLocalParameterfv;
	Gls::Opengltokens::PFNGLTEXIMAGE2DMULTISAMPLEPROC TexImage2DMultisample;
	Gls::Opengltokens::PFNGLTEXIMAGE3DMULTISAMPLEPROC TexImage3DMultisample;
	Gls::Opengltokens::PFNGLGETMULTISAMPLEFVPROC GetMultisamplefv;
	Gls::Opengltokens::PFNGLSAMPLEMASKIPROC SampleMaski;
	Gls::Opengltokens::PFNGLPROVOKINGVERTEXPROC ProvokingVertex;
	Gls::Opengltokens::PFNGLFENCESYNCPROC FenceSync;
	Gls::Opengltokens::PFNGLISSYNCPROC IsSync;
	Gls::Opengltokens::PFNGLDELETESYNCPROC DeleteSync;
	Gls::Opengltokens::PFNGLCLIENTWAITSYNCPROC ClientWaitSync;
	Gls::Opengltokens::PFNGLWAITSYNCPROC WaitSync;
	Gls::Opengltokens::PFNGLGETINTEGER64VPROC GetInteger64v;
	Gls::Opengltokens::PFNGLGETSYNCIVPROC GetSynciv;
	Gls::Opengltokens::PFNGLBLENDEQUATIONIPROC BlendEquationi;
	Gls::Opengltokens::PFNGLBLENDEQUATIONSEPARATEIPROC BlendEquationSeparatei;
	Gls::Opengltokens::PFNGLBLENDFUNCIPROC BlendFunci;
	Gls::Opengltokens::PFNGLBLENDFUNCSEPARATEIPROC BlendFuncSeparatei;
	Gls::Opengltokens::PFNGLMINSAMPLESHADINGPROC MinSampleShading;
	Gls::Opengltokens::PFNGLGENSAMPLERSPROC GenSamplers;
	Gls::Opengltokens::PFNGLDELETESAMPLERSPROC DeleteSamplers;
	Gls::Opengltokens::PFNGLISSAMPLERPROC IsSampler;
	Gls::Opengltokens::PFNGLBINDSAMPLERPROC BindSampler;
	Gls::Opengltokens::PFNGLSAMPLERPARAMETERIPROC SamplerParameteri;
	Gls::Opengltokens::PFNGLSAMPLERPARAMETERIVPROC SamplerParameteriv;
	Gls::Opengltokens::PFNGLSAMPLERPARAMETERFPROC SamplerParameterf;
	Gls::Opengltokens::PFNGLSAMPLERPARAMETERFVPROC SamplerParameterfv;
	Gls::Opengltokens::PFNGLSAMPLERPARAMETERIIVPROC SamplerParameterIiv;
	Gls::Opengltokens::PFNGLSAMPLERPARAMETERIUIVPROC SamplerParameterIuiv;
	Gls::Opengltokens::PFNGLGETSAMPLERPARAMETERIVPROC GetSamplerParameteriv;
	Gls::Opengltokens::PFNGLGETSAMPLERPARAMETERIIVPROC GetSamplerParameterIiv;
	Gls::Opengltokens::PFNGLGETSAMPLERPARAMETERFVPROC GetSamplerParameterfv;
	Gls::Opengltokens::PFNGLGETSAMPLERPARAMETERIFVPROC GetSamplerParameterIfv;
	Gls::Opengltokens::PFNGLCopyImageSubData CopyImageSubData;
	Gls::Opengltokens::PFNGLTexBufferRange TexBufferRange;
	Gls::Opengltokens::PFNGLTextureBufferRange TextureBufferRange;
	Gls::Opengltokens::PFNGLTexStorage2DMultisample TexStorage2DMultisample;
	Gls::Opengltokens::PFNGLTexStorage3DMultisample TexStorage3DMultisample;
	Gls::Opengltokens::PFNGLTextureStorage2DMultisample TextureStorage2DMultisample;
	Gls::Opengltokens::PFNGLTextureStorage3DMultisample TextureStorage3DMultisample;
	Gls::Opengltokens::PFNGLBufferStorage BufferStorage;
	Gls::Opengltokens::PFNGLClearTexImage ClearTexImage;
	Gls::Opengltokens::PFNGLClearTexSubImage ClearTexSubImage;
	Gls::Opengltokens::PFNGLBindBuffersBase BindBuffersBase;
	Gls::Opengltokens::PFNGLBindBuffersRange BindBuffersRange;
	Gls::Opengltokens::PFNGLBindTextures BindTextures;
	Gls::Opengltokens::PFNGLBindSamplers BindSamplers;
	Gls::Opengltokens::PFNGLBindImageTextures BindImageTextures;
	Gls::Opengltokens::PFNGLBindVertexBuffers BindVertexBuffers;
	Gls::Opengltokens::PFNGLTextureView TextureView;
	Gls::Opengltokens::PFNGLCLIENTATTRIBDEFAULTEXTPROC ClientAttribDefault;
	Gls::Opengltokens::PFNGLPUSHCLIENTATTRIBDEFAULTEXTPROC PushClientAttribDefault;
	Gls::Opengltokens::PFNGLMATRIXLOADFEXTPROC MatrixLoadf;
	Gls::Opengltokens::PFNGLMATRIXLOADDEXTPROC MatrixLoadd;
	Gls::Opengltokens::PFNGLMATRIXMULTFEXTPROC MatrixMultf;
	Gls::Opengltokens::PFNGLMATRIXMULTDEXTPROC MatrixMultd;
	Gls::Opengltokens::PFNGLMATRIXLOADIDENTITYEXTPROC MatrixLoadIdentity;
	Gls::Opengltokens::PFNGLMATRIXROTATEFEXTPROC MatrixRotatef;
	Gls::Opengltokens::PFNGLMATRIXROTATEDEXTPROC MatrixRotated;
	Gls::Opengltokens::PFNGLMATRIXSCALEFEXTPROC MatrixScalef;
	Gls::Opengltokens::PFNGLMATRIXSCALEDEXTPROC MatrixScaled;
	Gls::Opengltokens::PFNGLMATRIXTRANSLATEFEXTPROC MatrixTranslatef;
	Gls::Opengltokens::PFNGLMATRIXTRANSLATEDEXTPROC MatrixTranslated;
	Gls::Opengltokens::PFNGLMATRIXFRUSTUMEXTPROC MatrixFrustum;
	Gls::Opengltokens::PFNGLMATRIXORTHOEXTPROC MatrixOrtho;
	Gls::Opengltokens::PFNGLMATRIXPOPEXTPROC MatrixPop;
	Gls::Opengltokens::PFNGLMATRIXPUSHEXTPROC MatrixPush;
	Gls::Opengltokens::PFNGLMATRIXLOADTRANSPOSEFEXTPROC MatrixLoadTransposef;
	Gls::Opengltokens::PFNGLMATRIXLOADTRANSPOSEDEXTPROC MatrixLoadTransposed;
	Gls::Opengltokens::PFNGLMATRIXMULTTRANSPOSEFEXTPROC MatrixMultTransposef;
	Gls::Opengltokens::PFNGLMATRIXMULTTRANSPOSEDEXTPROC MatrixMultTransposed;
	Gls::Opengltokens::PFNGLTEXTUREPARAMETERFVEXTPROC TextureParameterfv;
	Gls::Opengltokens::PFNGLTEXTUREPARAMETERIEXTPROC TextureParameteri;
	Gls::Opengltokens::PFNGLTEXTUREPARAMETERIVEXTPROC TextureParameteriv;
	Gls::Opengltokens::PFNGLTEXTUREIMAGE1DEXTPROC TextureImage1D;
	Gls::Opengltokens::PFNGLTEXTUREIMAGE2DEXTPROC TextureImage2D;
	Gls::Opengltokens::PFNGLTEXTURESUBIMAGE1DEXTPROC TextureSubImage1D;
	Gls::Opengltokens::PFNGLTEXTURESUBIMAGE2DEXTPROC TextureSubImage2D;
	Gls::Opengltokens::PFNGLCOPYTEXTUREIMAGE1DEXTPROC CopyTextureImage1D;
	Gls::Opengltokens::PFNGLCOPYTEXTUREIMAGE2DEXTPROC CopyTextureImage2D;
	Gls::Opengltokens::PFNGLCOPYTEXTURESUBIMAGE1DEXTPROC CopyTextureSubImage1D;
	Gls::Opengltokens::PFNGLCOPYTEXTURESUBIMAGE2DEXTPROC CopyTextureSubImage2D;
	Gls::Opengltokens::PFNGLGETTEXTUREIMAGEEXTPROC GetTextureImage;
	Gls::Opengltokens::PFNGLGETTEXTUREPARAMETERFVEXTPROC GetTextureParameterfv;
	Gls::Opengltokens::PFNGLGETTEXTUREPARAMETERIVEXTPROC GetTextureParameteriv;
	Gls::Opengltokens::PFNGLGETTEXTURELEVELPARAMETERFVEXTPROC GetTextureLevelParameterfv;
	Gls::Opengltokens::PFNGLGETTEXTURELEVELPARAMETERIVEXTPROC GetTextureLevelParameteriv;
	Gls::Opengltokens::PFNGLTEXTUREIMAGE3DEXTPROC TextureImage3D;
	Gls::Opengltokens::PFNGLTEXTURESUBIMAGE3DEXTPROC TextureSubImage3D;
	Gls::Opengltokens::PFNGLCOPYTEXTURESUBIMAGE3DEXTPROC CopyTextureSubImage3D;
	Gls::Opengltokens::PFNGLMULTITEXPARAMETERFEXTPROC MultiTexParameterf;
	Gls::Opengltokens::PFNGLMULTITEXPARAMETERFVEXTPROC MultiTexParameterfv;
	Gls::Opengltokens::PFNGLMULTITEXPARAMETERIEXTPROC MultiTexParameteri;
	Gls::Opengltokens::PFNGLMULTITEXPARAMETERIVEXTPROC MultiTexParameteriv;
	Gls::Opengltokens::PFNGLMULTITEXIMAGE1DEXTPROC MultiTexImage1D;
	Gls::Opengltokens::PFNGLMULTITEXIMAGE2DEXTPROC MultiTexImage2D;
	Gls::Opengltokens::PFNGLMULTITEXSUBIMAGE1DEXTPROC MultiTexSubImage1D;
	Gls::Opengltokens::PFNGLMULTITEXSUBIMAGE2DEXTPROC MultiTexSubImage2D;
	Gls::Opengltokens::PFNGLCOPYMULTITEXIMAGE1DEXTPROC CopyMultiTexImage1D;
	Gls::Opengltokens::PFNGLCOPYMULTITEXIMAGE2DEXTPROC CopyMultiTexImage2D;
	Gls::Opengltokens::PFNGLCOPYMULTITEXSUBIMAGE1DEXTPROC CopyMultiTexSubImage1D;
	Gls::Opengltokens::PFNGLCOPYMULTITEXSUBIMAGE2DEXTPROC CopyMultiTexSubImage2D;
	Gls::Opengltokens::PFNGLGETMULTITEXIMAGEEXTPROC GetMultiTexImage;
	Gls::Opengltokens::PFNGLGETMULTITEXPARAMETERFVEXTPROC GetMultiTexParameterfv;
	Gls::Opengltokens::PFNGLGETMULTITEXPARAMETERIVEXTPROC GetMultiTexParameteriv;
	Gls::Opengltokens::PFNGLGETMULTITEXLEVELPARAMETERFVEXTPROC GetMultiTexLevelParameterfv;
	Gls::Opengltokens::PFNGLGETMULTITEXLEVELPARAMETERIVEXTPROC GetMultiTexLevelParameteriv;
	Gls::Opengltokens::PFNGLMULTITEXIMAGE3DEXTPROC MultiTexImage3D;
	Gls::Opengltokens::PFNGLMULTITEXSUBIMAGE3DEXTPROC MultiTexSubImage3D;
	Gls::Opengltokens::PFNGLCOPYMULTITEXSUBIMAGE3DEXTPROC CopyMultiTexSubImage3D;
	Gls::Opengltokens::PFNGLBINDMULTITEXTUREEXTPROC BindMultiTexture;
	Gls::Opengltokens::PFNGLENABLECLIENTSTATEINDEXEDEXTPROC EnableClientStateIndexed;
	Gls::Opengltokens::PFNGLDISABLECLIENTSTATEINDEXEDEXTPROC DisableClientStateIndexed;
	Gls::Opengltokens::PFNGLMULTITEXCOORDPOINTEREXTPROC MultiTexCoordPointer;
	Gls::Opengltokens::PFNGLMULTITEXENVFEXTPROC MultiTexEnvf;
	Gls::Opengltokens::PFNGLMULTITEXENVFVEXTPROC MultiTexEnvfv;
	Gls::Opengltokens::PFNGLMULTITEXENVIEXTPROC MultiTexEnvi;
	Gls::Opengltokens::PFNGLMULTITEXENVIVEXTPROC MultiTexEnviv;
	Gls::Opengltokens::PFNGLMULTITEXGENDEXTPROC MultiTexGend;
	Gls::Opengltokens::PFNGLMULTITEXGENDVEXTPROC MultiTexGendv;
	Gls::Opengltokens::PFNGLMULTITEXGENFEXTPROC MultiTexGenf;
	Gls::Opengltokens::PFNGLMULTITEXGENFVEXTPROC MultiTexGenfv;
	Gls::Opengltokens::PFNGLMULTITEXGENIEXTPROC MultiTexGeni;
	Gls::Opengltokens::PFNGLMULTITEXGENIVEXTPROC MultiTexGeniv;
	Gls::Opengltokens::PFNGLGETMULTITEXENVFVEXTPROC GetMultiTexEnvfv;
	Gls::Opengltokens::PFNGLGETMULTITEXENVIVEXTPROC GetMultiTexEnviv;
	Gls::Opengltokens::PFNGLGETMULTITEXGENDVEXTPROC GetMultiTexGendv;
	Gls::Opengltokens::PFNGLGETMULTITEXGENFVEXTPROC GetMultiTexGenfv;
	Gls::Opengltokens::PFNGLGETMULTITEXGENIVEXTPROC GetMultiTexGeniv;
	Gls::Opengltokens::PFNGLGETFLOATINDEXEDVEXTPROC GetFloatIndexedv;
	Gls::Opengltokens::PFNGLGETDOUBLEINDEXEDVEXTPROC GetDoubleIndexedv;
	Gls::Opengltokens::PFNGLGETPOINTERINDEXEDVEXTPROC GetPointerIndexedv;
	Gls::Opengltokens::PFNGLCOMPRESSEDTEXTUREIMAGE3DEXTPROC CompressedTextureImage3D;
	Gls::Opengltokens::PFNGLCOMPRESSEDTEXTUREIMAGE2DEXTPROC CompressedTextureImage2D;
	Gls::Opengltokens::PFNGLCOMPRESSEDTEXTUREIMAGE1DEXTPROC CompressedTextureImage1D;
	Gls::Opengltokens::PFNGLCOMPRESSEDTEXTURESUBIMAGE3DEXTPROC CompressedTextureSubImage3D;
	Gls::Opengltokens::PFNGLCOMPRESSEDTEXTURESUBIMAGE2DEXTPROC CompressedTextureSubImage2D;
	Gls::Opengltokens::PFNGLCOMPRESSEDTEXTURESUBIMAGE1DEXTPROC CompressedTextureSubImage1D;
	Gls::Opengltokens::PFNGLGETCOMPRESSEDTEXTUREIMAGEEXTPROC GetCompressedTextureImage;
	Gls::Opengltokens::PFNGLCOMPRESSEDMULTITEXIMAGE3DEXTPROC CompressedMultiTexImage3D;
	Gls::Opengltokens::PFNGLCOMPRESSEDMULTITEXIMAGE2DEXTPROC CompressedMultiTexImage2D;
	Gls::Opengltokens::PFNGLCOMPRESSEDMULTITEXIMAGE1DEXTPROC CompressedMultiTexImage1D;
	Gls::Opengltokens::PFNGLCOMPRESSEDMULTITEXSUBIMAGE3DEXTPROC CompressedMultiTexSubImage3D;
	Gls::Opengltokens::PFNGLCOMPRESSEDMULTITEXSUBIMAGE2DEXTPROC CompressedMultiTexSubImage2D;
	Gls::Opengltokens::PFNGLCOMPRESSEDMULTITEXSUBIMAGE1DEXTPROC CompressedMultiTexSubImage1D;
	Gls::Opengltokens::PFNGLGETCOMPRESSEDMULTITEXIMAGEEXTPROC GetCompressedMultiTexImage;
	Gls::Opengltokens::PFNGLNAMEDPROGRAMSTRINGEXTPROC NamedProgramString;
	Gls::Opengltokens::PFNGLNAMEDPROGRAMLOCALPARAMETER4DEXTPROC NamedProgramLocalParameter4d;
	Gls::Opengltokens::PFNGLNAMEDPROGRAMLOCALPARAMETER4DVEXTPROC NamedProgramLocalParameter4dv;
	Gls::Opengltokens::PFNGLNAMEDPROGRAMLOCALPARAMETER4FEXTPROC NamedProgramLocalParameter4f;
	Gls::Opengltokens::PFNGLNAMEDPROGRAMLOCALPARAMETER4FVEXTPROC NamedProgramLocalParameter4fv;
	Gls::Opengltokens::PFNGLGETNAMEDPROGRAMLOCALPARAMETERDVEXTPROC GetNamedProgramLocalParameterdv;
	Gls::Opengltokens::PFNGLGETNAMEDPROGRAMLOCALPARAMETERFVEXTPROC GetNamedProgramLocalParameterfv;
	Gls::Opengltokens::PFNGLGETNAMEDPROGRAMIVEXTPROC GetNamedProgramiv;
	Gls::Opengltokens::PFNGLGETNAMEDPROGRAMSTRINGEXTPROC GetNamedProgramString;
	Gls::Opengltokens::PFNGLNAMEDPROGRAMLOCALPARAMETERS4FVEXTPROC NamedProgramLocalParameters4fv;
	Gls::Opengltokens::PFNGLNAMEDPROGRAMLOCALPARAMETERI4IEXTPROC NamedProgramLocalParameterI4i;
	Gls::Opengltokens::PFNGLNAMEDPROGRAMLOCALPARAMETERI4IVEXTPROC NamedProgramLocalParameterI4iv;
	Gls::Opengltokens::PFNGLNAMEDPROGRAMLOCALPARAMETERSI4IVEXTPROC NamedProgramLocalParametersI4iv;
	Gls::Opengltokens::PFNGLNAMEDPROGRAMLOCALPARAMETERI4UIEXTPROC NamedProgramLocalParameterI4ui;
	Gls::Opengltokens::PFNGLNAMEDPROGRAMLOCALPARAMETERI4UIVEXTPROC NamedProgramLocalParameterI4uiv;
	Gls::Opengltokens::PFNGLNAMEDPROGRAMLOCALPARAMETERSI4UIVEXTPROC NamedProgramLocalParametersI4uiv;
	Gls::Opengltokens::PFNGLGETNAMEDPROGRAMLOCALPARAMETERIIVEXTPROC GetNamedProgramLocalParameterIiv;
	Gls::Opengltokens::PFNGLGETNAMEDPROGRAMLOCALPARAMETERIUIVEXTPROC GetNamedProgramLocalParameterIuiv;
	Gls::Opengltokens::PFNGLTEXTUREPARAMETERIIVEXTPROC TextureParameterIiv;
	Gls::Opengltokens::PFNGLTEXTUREPARAMETERIUIVEXTPROC TextureParameterIuiv;
	Gls::Opengltokens::PFNGLGETTEXTUREPARAMETERIIVEXTPROC GetTextureParameterIiv;
	Gls::Opengltokens::PFNGLGETTEXTUREPARAMETERIUIVEXTPROC GetTextureParameterIuiv;
	Gls::Opengltokens::PFNGLMULTITEXPARAMETERIIVEXTPROC MultiTexParameterIiv;
	Gls::Opengltokens::PFNGLMULTITEXPARAMETERIUIVEXTPROC MultiTexParameterIuiv;
	Gls::Opengltokens::PFNGLGETMULTITEXPARAMETERIIVEXTPROC GetMultiTexParameterIiv;
	Gls::Opengltokens::PFNGLGETMULTITEXPARAMETERIUIVEXTPROC GetMultiTexParameterIuiv;
	Gls::Opengltokens::PFNGLNAMEDBUFFERDATAEXTPROC NamedBufferData;
	Gls::Opengltokens::PFNGLNAMEDBUFFERSUBDATAEXTPROC NamedBufferSubData;
	Gls::Opengltokens::PFNGLMAPNAMEDBUFFEREXTPROC MapNamedBuffer;
	Gls::Opengltokens::PFNGLUNMAPNAMEDBUFFEREXTPROC UnmapNamedBuffer;
	Gls::Opengltokens::PFNGLMAPNAMEDBUFFERRANGEEXTPROC MapNamedBufferRange;
	Gls::Opengltokens::PFNGLFLUSHMAPPEDNAMEDBUFFERRANGEEXTPROC FlushMappedNamedBufferRange;
	Gls::Opengltokens::PFNGLNAMEDCOPYBUFFERSUBDATAEXTPROC NamedCopyBufferSubData;
	Gls::Opengltokens::PFNGLGETNAMEDBUFFERPARAMETERIVEXTPROC GetNamedBufferParameteriv;
	Gls::Opengltokens::PFNGLGETNAMEDBUFFERPOINTERVEXTPROC GetNamedBufferPointerv;
	Gls::Opengltokens::PFNGLGETNAMEDBUFFERSUBDATAEXTPROC GetNamedBufferSubData;
	Gls::Opengltokens::PFNGLTEXTUREBUFFEREXTPROC TextureBuffer;
	Gls::Opengltokens::PFNGLMULTITEXBUFFEREXTPROC MultiTexBuffer;
	Gls::Opengltokens::PFNGLNAMEDRENDERBUFFERSTORAGEEXTPROC NamedRenderbufferStorage;
	Gls::Opengltokens::PFNGLGETNAMEDRENDERBUFFERPARAMETERIVEXTPROC GetNamedRenderbufferParameteriv;
	Gls::Opengltokens::PFNGLCHECKNAMEDFRAMEBUFFERSTATUSEXTPROC CheckNamedFramebufferStatus;
	Gls::Opengltokens::PFNGLNAMEDFRAMEBUFFERTEXTURE1DEXTPROC NamedFramebufferTexture1D;
	Gls::Opengltokens::PFNGLNAMEDFRAMEBUFFERTEXTURE2DEXTPROC NamedFramebufferTexture2D;
	Gls::Opengltokens::PFNGLNAMEDFRAMEBUFFERTEXTURE3DEXTPROC NamedFramebufferTexture3D;
	Gls::Opengltokens::PFNGLNAMEDFRAMEBUFFERRENDERBUFFEREXTPROC NamedFramebufferRenderbuffer;
	Gls::Opengltokens::PFNGLGETNAMEDFRAMEBUFFERATTACHMENTPARAMETERIVEXTPROC GetNamedFramebufferAttachmentParameteriv;
	Gls::Opengltokens::PFNGLGENERATETEXTUREMIPMAPEXTPROC GenerateTextureMipmap;
	Gls::Opengltokens::PFNGLGENERATEMULTITEXMIPMAPEXTPROC GenerateMultiTexMipmap;
	Gls::Opengltokens::PFNGLFRAMEBUFFERDRAWBUFFEREXTPROC FramebufferDrawBuffer;
	Gls::Opengltokens::PFNGLFRAMEBUFFERDRAWBUFFERSEXTPROC FramebufferDrawBuffers;
	Gls::Opengltokens::PFNGLFRAMEBUFFERREADBUFFEREXTPROC FramebufferReadBuffer;
	Gls::Opengltokens::PFNGLGETFRAMEBUFFERPARAMETERIVEXTPROC GetFramebufferParameteriv;
	Gls::Opengltokens::PFNGLNAMEDRENDERBUFFERSTORAGEMULTISAMPLEEXTPROC NamedRenderbufferStorageMultisample;
	Gls::Opengltokens::PFNGLNAMEDRENDERBUFFERSTORAGEMULTISAMPLECOVERAGEEXTPROC NamedRenderbufferStorageMultisampleCoverage;
	Gls::Opengltokens::PFNGLNAMEDFRAMEBUFFERTEXTUREEXTPROC NamedFramebufferTexture;
	Gls::Opengltokens::PFNGLNAMEDFRAMEBUFFERTEXTURELAYEREXTPROC NamedFramebufferTextureLayer;
	Gls::Opengltokens::PFNGLNAMEDFRAMEBUFFERTEXTUREFACEEXTPROC NamedFramebufferTextureFace;
	Gls::Opengltokens::PFNGLTEXTURERENDERBUFFEREXTPROC TextureRenderbuffer;
	Gls::Opengltokens::PFNGLMULTITEXRENDERBUFFEREXTPROC MultiTexRenderbuffer;
	Gls::Opengltokens::PFNGLFRAMETERMINATORGREMEDYPROC FrameTerminatorGREMEDY;
	Gls::Opengltokens::PFNGLSTRINGMARKERGREMEDYPROC StringMarkerGREMEDY;
	void __fastcall (*DebugMessageEnableAMDX)(unsigned category, unsigned severity, int Count, unsigned &ids, bool Enabled);
	Gls::Opengltokens::PFNGLPushDebugGroup PushDebugGroup;
	Gls::Opengltokens::PFNGLPopDebugGroup PopDebugGroup;
	Gls::Opengltokens::PFNGLObjectLabel ObjectLabel;
	Gls::Opengltokens::PFNGLGetObjectLabel GetObjectLabel;
	Gls::Opengltokens::PFNGLObjectPtrLabel ObjectPtrLabel;
	Gls::Opengltokens::PFNGLGetObjectPtrLabel GetObjectPtrLabel;
	void __stdcall (*DebugMessageCallbackAMDX)(Gls::Opengltokens::TDebugProcAMD callback, void * userParam);
	void __stdcall (*DebugMessageControl)(unsigned type_, unsigned Source, unsigned severity, int Count, unsigned &ids, bool Enabled);
	void __stdcall (*DebugMessageInsert)(unsigned Source, unsigned severity, unsigned id, int length, const char * buf);
	void __stdcall (*DebugMessageCallback)(Gls::Opengltokens::TDebugProc callback, void * userParam);
	unsigned __stdcall (*GetDebugMessageLog)(unsigned Count, int bufSize, unsigned &severity, unsigned &severities, unsigned &ids, int &lengths, char * messageLog);
	Gls::Opengltokens::PFNGLCreateSyncFromCLevent CreateSyncFromCLevent;
	void __stdcall (*VDPAUInitNV)(const void * vdpDevice, const void * getProcAddress);
	void __stdcall (*VDPAUFiniNV)(void);
	NativeInt __stdcall (*VDPAURegisterVideoSurfaceNV)(const void * vdpSurface, unsigned target, int numTextureNames, const System::PCardinal textureNames);
	NativeInt __stdcall (*VDPAURegisterOutputSurfaceNV)(const void * vdpSurface, unsigned target, int numTextureNames, const System::PCardinal textureNames);
	void __stdcall (*VDPAUIsSurfaceNV)(NativeInt surface);
	void __stdcall (*VDPAUUnregisterSurfaceNV)(NativeInt surface);
	void __stdcall (*VDPAUGetSurfaceivNV)(NativeInt surface, unsigned pname, int bufSize, System::PInteger length, System::PInteger values);
	void __stdcall (*VDPAUSurfaceAccessNV)(NativeInt surface, unsigned access);
	void __stdcall (*VDPAUMapSurfacesNV)(int numSurfaces, const Gls::Opengltokens::PGLvdpauSurfaceNV surfaces);
	void __stdcall (*VDPAUUnmapSurfacesNV)(int numSurface, const Gls::Opengltokens::PGLvdpauSurfaceNV surfaces);
	Gls::Opengltokens::PFNGLGENPATHSNVPROC GenPathsNV;
	Gls::Opengltokens::PFNGLDELETEPATHSNVPROC DeletePathsNV;
	Gls::Opengltokens::PFNGLISPATHNVPROC IsPathNV;
	Gls::Opengltokens::PFNGLPATHCOMMANDSNVPROC PathCommandsNV;
	Gls::Opengltokens::PFNGLPATHCOORDSNVPROC PathCoordsNV;
	Gls::Opengltokens::PFNGLPATHSUBCOMMANDSNVPROC PathSubCommandsNV;
	Gls::Opengltokens::PFNGLPATHSUBCOORDSNVPROC PathSubCoordsNV;
	Gls::Opengltokens::PFNGLPATHSTRINGNVPROC PathStringNV;
	Gls::Opengltokens::PFNGLPATHGLYPHSNVPROC PathGlyphsNV;
	Gls::Opengltokens::PFNGLPATHGLYPHRANGENVPROC PathGlyphRangeNV;
	Gls::Opengltokens::PFNGLWEIGHTPATHSNVPROC WeightPathsNV;
	Gls::Opengltokens::PFNGLCOPYPATHNVPROC CopyPathNV;
	Gls::Opengltokens::PFNGLINTERPOLATEPATHSNVPROC InterpolatePathsNV;
	Gls::Opengltokens::PFNGLPATHPARAMETERIVNVPROC PathParameterivNV;
	Gls::Opengltokens::PFNGLPATHPARAMETERINVPROC PathParameteriNV;
	Gls::Opengltokens::PFNGLPATHPARAMETERFVNVPROC PathParameterfvNV;
	Gls::Opengltokens::PFNGLPATHPARAMETERFNVPROC PathParameterfNV;
	Gls::Opengltokens::PFNGLPATHDASHARRAYNVPROC PathDashArrayNV;
	Gls::Opengltokens::PFNGLPATHSTENCILFUNCNVPROC PathStencilFuncNV;
	Gls::Opengltokens::PFNGLSTENCILFILLPATHNVPROC StencilFillPathNV;
	Gls::Opengltokens::PFNGLSTENCILSTROKEPATHNVPROC StencilStrokePathNV;
	Gls::Opengltokens::PFNGLSTENCILFILLPATHINSTANCEDNVPROC StencilFillPathInstancedNV;
	Gls::Opengltokens::PFNGLSTENCILSTROKEPATHINSTANCEDNVPROC StencilStrokePathInstancedNV;
	Gls::Opengltokens::PFNGLPATHCOLORGENNVPROC PathColorGenNV;
	Gls::Opengltokens::PFNGLPATHTEXGENNVPROC PathTexGenNV;
	Gls::Opengltokens::PFNGLPATHFOGGENNVPROC PathFogGenNV;
	Gls::Opengltokens::PFNGLCOVERFILLPATHNVPROC CoverFillPathNV;
	Gls::Opengltokens::PFNGLCOVERSTROKEPATHNVPROC CoverStrokePathNV;
	Gls::Opengltokens::PFNGLCOVERFILLPATHINSTANCEDNVPROC CoverFillPathInstancedNV;
	Gls::Opengltokens::PFNGLCOVERSTROKEPATHINSTANCEDNVPROC CoverStrokePathInstancedNV;
	Gls::Opengltokens::PFNGLGETPATHPARAMETERIVNVPROC GetPathParameterivNV;
	Gls::Opengltokens::PFNGLGETPATHPARAMETERFVNVPROC GetPathParameterfvNV;
	Gls::Opengltokens::PFNGLGETPATHCOMMANDSNVPROC GetPathCommandsNV;
	Gls::Opengltokens::PFNGLGETPATHCOORDSNVPROC GetPathCoordsNV;
	Gls::Opengltokens::PFNGLGETPATHDASHARRAYNVPROC GetPathDashArrayNV;
	Gls::Opengltokens::PFNGLGETPATHMETRICSNVPROC GetPathMetricsNV;
	Gls::Opengltokens::PFNGLGETPATHMETRICRANGENVPROC GetPathMetricRangeNV;
	Gls::Opengltokens::PFNGLGETPATHSPACINGNVPROC GetPathSpacingNV;
	Gls::Opengltokens::PFNGLGETPATHCOLORGENIVNVPROC GetPathColorGenivNV;
	Gls::Opengltokens::PFNGLGETPATHCOLORGENFVNVPROC GetPathColorGenfvNV;
	Gls::Opengltokens::PFNGLGETPATHTEXGENIVNVPROC GetPathTexGenivNV;
	Gls::Opengltokens::PFNGLGETPATHTEXGENFVNVPROC GetPathTexGenfvNV;
	Gls::Opengltokens::PFNGLISPOINTINFILLPATHNVPROC IsPointInFillPathNV;
	Gls::Opengltokens::PFNGLISPOINTINSTROKEPATHNVPROC IsPointInStrokePathNV;
	Gls::Opengltokens::PFNGLGETPATHLENGTHNVPROC GetPathLengthNV;
	Gls::Opengltokens::PFNGLPOINTALONGPATHNVPROC PointAlongPathNV;
	Gls::Opengltokens::PFNGLPATHSTENCILDEPTHOFFSETNVPROC PathStencilDepthOffsetNV;
	Gls::Opengltokens::PFNGLPATHCOVERDEPTHFUNCNVPROC PathCoverDepthFuncNV;
	bool W_ARB_buffer_region;
	bool W_ARB_create_context;
	bool W_ARB_create_context_profile;
	bool W_ARB_extensions_string;
	bool W_ARB_framebuffer_sRGB;
	bool W_ARB_make_current_read;
	bool W_ARB_multisample;
	bool W_ARB_pbuffer;
	bool W_ARB_pixel_format;
	bool W_ARB_pixel_format_float;
	bool W_ARB_render_texture;
	bool W_ATI_pixel_format_float;
	bool W_EXT_framebuffer_sRGB;
	bool W_EXT_pixel_format_packed_float;
	bool W_EXT_swap_control;
	bool W_NV_gpu_affinity;
	bool W_EXT_create_context_es2_profile;
	bool W_NV_DX_interop;
	bool W_NV_DX_interop2;
	Gls::Opengltokens::PFNWGLCREATEBUFFERREGIONARBPROC WCreateBufferRegionARB;
	Gls::Opengltokens::PFNWGLDELETEBUFFERREGIONARBPROC WDeleteBufferRegionARB;
	Gls::Opengltokens::PFNWGLSAVEBUFFERREGIONARBPROC WSaveBufferRegionARB;
	Gls::Opengltokens::PFNWGLRESTOREBUFFERREGIONARBPROC WRestoreBufferRegionARB;
	Gls::Opengltokens::PFNWGLGETEXTENSIONSSTRINGARBPROC WGetExtensionsStringARB;
	Gls::Opengltokens::PFNWGLGETPIXELFORMATATTRIBIVARBPROC WGetPixelFormatAttribivARB;
	Gls::Opengltokens::PFNWGLGETPIXELFORMATATTRIBFVARBPROC WGetPixelFormatAttribfvARB;
	Gls::Opengltokens::PFNWGLCHOOSEPIXELFORMATARBPROC WChoosePixelFormatARB;
	Gls::Opengltokens::PFNWGLMAKECONTEXTCURRENTARBPROC WMakeContextCurrentARB;
	Gls::Opengltokens::PFNWGLGETCURRENTREADDCARBPROC WGetCurrentReadDCARB;
	Gls::Opengltokens::PFNWGLCREATEPBUFFERARBPROC WCreatePbufferARB;
	Gls::Opengltokens::PFNWGLGETPBUFFERDCARBPROC WGetPbufferDCARB;
	Gls::Opengltokens::PFNWGLRELEASEPBUFFERDCARBPROC WReleasePbufferDCARB;
	Gls::Opengltokens::PFNWGLDESTROYPBUFFERARBPROC WDestroyPbufferARB;
	Gls::Opengltokens::PFNWGLQUERYPBUFFERARBPROC WQueryPbufferARB;
	Gls::Opengltokens::PFNWGLBINDTEXIMAGEARBPROC WBindTexImageARB;
	Gls::Opengltokens::PFNWGLRELEASETEXIMAGEARBPROC WReleaseTexImageARB;
	Gls::Opengltokens::PFNWGLSETPBUFFERATTRIBARBPROC WSetPbufferAttribARB;
	Gls::Opengltokens::PFNWGLCREATECONTEXTATTRIBSARBPROC WCreateContextAttribsARB;
	Gls::Opengltokens::PFNWGLENUMGPUSNVPROC WEnumGpusNV;
	Gls::Opengltokens::PFNWGLENUMGPUDEVICESNVPROC WEnumGpuDevicesNV;
	Gls::Opengltokens::PFNWGLCREATEAFFINITYDCNVPROC WCreateAffinityDCNV;
	Gls::Opengltokens::PFNWGLENUMGPUSFROMAFFINITYDCNVPROC WEnumGpusFromAffinityDCNV;
	Gls::Opengltokens::PFNWGLDELETEDCNVPROC WDeleteDCNV;
	Gls::Opengltokens::PFNWGLDXSETRESOURCESHAREHANDLEPROC WDXSetResourceShareHandleNV;
	Gls::Opengltokens::PFNWGLDXOPENDEVICEPROC WDXOpenDeviceNV;
	Gls::Opengltokens::PFNWGLDXCLOSEDEVICEPROC WDXCloseDeviceNV;
	Gls::Opengltokens::PFNWGLDXREGISTEROBJECTPROC WDXRegisterObjectNV;
	Gls::Opengltokens::PFNWGLDXUNREGISTEROBJECTPROC WDXUnregisterObjectNV;
	Gls::Opengltokens::PFNWGLDXOBJECTACCESSPROC WDXObjectAccessNV;
	Gls::Opengltokens::PFNWGLDXLOCKOBJECTSPROC WDXLockObjectsNV;
	Gls::Opengltokens::PFNWGLDXUNLOCKOBJECTSNVPROC WDXUnlockObjectsNV;
	Gls::Opengltokens::PFNWGLSWAPINTERVALEXTPROC WSwapIntervalEXT;
	Gls::Opengltokens::PFNWGLGETSWAPINTERVALEXTPROC WGetSwapIntervalEXT;
	Gls::Opengltokens::PFNWGLALLOCATEMEMORYNVPROC WAllocateMemoryNV;
	Gls::Opengltokens::PFNWGLFREEMEMORYNVPROC WFreeMemoryNV;
	void __stdcall (*UNurbsCallbackDataEXT)(Gls::Opengltokens::PGLUNurbs nurb, void * userData);
	Gls::Opengltokens::PGLUNurbs __stdcall (*UNewNurbsTessellatorEXT)(void);
	void __stdcall (*UDeleteNurbsTessellatorEXT)(Gls::Opengltokens::PGLUNurbs nurb);
	__fastcall TGLExtensionsAndEntryPoints();
	void __fastcall Initialize(bool ATemporary = false);
	void __fastcall Close();
	void __fastcall CheckError();
	void __fastcall ClearError();
	__property bool IsInitialized = {read=FInitialized, nodefault};
	__property bool DebugMode = {read=FDebug, write=FDebug, nodefault};
public:
	/* TObject.Destroy */ inline __fastcall virtual ~TGLExtensionsAndEntryPoints() { }
	
};

#pragma pack(pop)

//-- var, const, procedure ---------------------------------------------------
#define opengl32 L"OpenGL32.dll"
#define glu32 L"GLU32.dll"
extern "C" System::LongBool __stdcall wglCopyContext(HGLRC p1, HGLRC p2, unsigned p3);
extern "C" HGLRC __stdcall wglCreateContext(HDC DC);
extern "C" HGLRC __stdcall wglCreateLayerContext(HDC p1, int p2);
extern "C" System::LongBool __stdcall wglDeleteContext(HGLRC p1);
extern "C" HGLRC __stdcall wglGetCurrentContext(void);
extern "C" HDC __stdcall wglGetCurrentDC(void);
extern "C" System::LongBool __stdcall wglMakeCurrent(HDC DC, HGLRC p2);
extern "C" System::LongBool __stdcall wglRealizeLayerPalette(HDC p1, int p2, System::LongBool p3);
extern "C" System::LongBool __stdcall wglShareLists(HGLRC p1, HGLRC p2);
extern "C" System::LongBool __stdcall wglSwapLayerBuffers(HDC p1, unsigned p2);
extern "C" char * __stdcall gluErrorString(unsigned errCode);
extern "C" char * __stdcall gluGetString(unsigned Name);
extern "C" void __stdcall gluOrtho2D(double left, double right, double bottom, double top);
extern "C" void __stdcall gluPerspective(double fovy, double aspect, double zNear, double zFar);
extern "C" void __stdcall gluPickMatrix(double X, double y, double Width, double Height, const Gls::Vectortypes::TVector4i &Viewport);
extern "C" void __stdcall gluLookAt(double eyex, double eyey, double eyez, double centerx, double centery, double centerz, double upx, double upy, double upz);
extern "C" int __stdcall gluProject(double objx, double objy, double objz, const Gls::Vectortypes::TMatrix4d &modelMatrix, const Gls::Vectortypes::TMatrix4d &projMatrix, const Gls::Vectortypes::TVector4i &Viewport, System::PDouble winx, System::PDouble winy, System::PDouble winz);
extern "C" int __stdcall gluUnProject(double winx, double winy, double winz, const Gls::Vectortypes::TMatrix4d &modelMatrix, const Gls::Vectortypes::TMatrix4d &projMatrix, const Gls::Vectortypes::TVector4i &Viewport, System::PDouble objx, System::PDouble objy, System::PDouble objz);
extern "C" int __stdcall gluScaleImage(unsigned format, int widthin, int heightin, unsigned typein, void * datain, int widthout, int heightout, unsigned typeout, void * dataout);
extern "C" int __stdcall gluBuild1DMipmaps(unsigned target, int Components, int Width, unsigned format, unsigned atype, void * Data);
extern "C" int __stdcall gluBuild2DMipmaps(unsigned target, int Components, int Width, int Height, unsigned format, unsigned atype, void * Data);
extern "C" Gls::Opengltokens::PGLUQuadric __stdcall gluNewQuadric(void);
extern "C" void __stdcall gluDeleteQuadric(Gls::Opengltokens::PGLUQuadric state);
extern "C" void __stdcall gluQuadricNormals(Gls::Opengltokens::PGLUQuadric quadObject, unsigned normals);
extern "C" void __stdcall gluQuadricTexture(Gls::Opengltokens::PGLUQuadric quadObject, System::ByteBool textureCoords);
extern "C" void __stdcall gluQuadricOrientation(Gls::Opengltokens::PGLUQuadric quadObject, unsigned orientation);
extern "C" void __stdcall gluQuadricDrawStyle(Gls::Opengltokens::PGLUQuadric quadObject, unsigned drawStyle);
extern "C" void __stdcall gluCylinder(Gls::Opengltokens::PGLUQuadric quadObject, double baseRadius, double topRadius, double Height, int slices, int stacks);
extern "C" void __stdcall gluDisk(Gls::Opengltokens::PGLUQuadric quadObject, double innerRadius, double outerRadius, int slices, int loops);
extern "C" void __stdcall gluPartialDisk(Gls::Opengltokens::PGLUQuadric quadObject, double innerRadius, double outerRadius, int slices, int loops, double startAngle, double sweepAngle);
extern "C" void __stdcall gluSphere(Gls::Opengltokens::PGLUQuadric quadObject, double radius, int slices, int stacks);
extern "C" void __stdcall gluQuadricCallback(Gls::Opengltokens::PGLUQuadric quadObject, unsigned which, Gls::Opengltokens::TGLUQuadricErrorProc fn);
extern "C" Gls::Opengltokens::PGLUTesselator __stdcall gluNewTess(void);
extern "C" void __stdcall gluDeleteTess(Gls::Opengltokens::PGLUTesselator tess);
extern "C" void __stdcall gluTessBeginPolygon(Gls::Opengltokens::PGLUTesselator tess, void * polygon_data);
extern "C" void __stdcall gluTessBeginContour(Gls::Opengltokens::PGLUTesselator tess);
extern "C" void __stdcall gluTessVertex(Gls::Opengltokens::PGLUTesselator tess, const Gls::Vectortypes::TVector3d &coords, void * Data);
extern "C" void __stdcall gluTessEndContour(Gls::Opengltokens::PGLUTesselator tess);
extern "C" void __stdcall gluTessEndPolygon(Gls::Opengltokens::PGLUTesselator tess);
extern "C" void __stdcall gluTessProperty(Gls::Opengltokens::PGLUTesselator tess, unsigned which, double Value);
extern "C" void __stdcall gluTessNormal(Gls::Opengltokens::PGLUTesselator tess, double X, double y, double z);
extern "C" void __stdcall gluTessCallback(Gls::Opengltokens::PGLUTesselator tess, unsigned which, void * fn);
extern "C" void __stdcall gluGetTessProperty(Gls::Opengltokens::PGLUTesselator tess, unsigned which, System::PDouble Value);
extern "C" Gls::Opengltokens::PGLUNurbs __stdcall gluNewNurbsRenderer(void);
extern "C" void __stdcall gluDeleteNurbsRenderer(Gls::Opengltokens::PGLUNurbs nobj);
extern "C" void __stdcall gluBeginSurface(Gls::Opengltokens::PGLUNurbs nobj);
extern "C" void __stdcall gluBeginCurve(Gls::Opengltokens::PGLUNurbs nobj);
extern "C" void __stdcall gluEndCurve(Gls::Opengltokens::PGLUNurbs nobj);
extern "C" void __stdcall gluEndSurface(Gls::Opengltokens::PGLUNurbs nobj);
extern "C" void __stdcall gluBeginTrim(Gls::Opengltokens::PGLUNurbs nobj);
extern "C" void __stdcall gluEndTrim(Gls::Opengltokens::PGLUNurbs nobj);
extern "C" void __stdcall gluPwlCurve(Gls::Opengltokens::PGLUNurbs nobj, int Count, System::PSingle points, int stride, unsigned atype);
extern "C" void __stdcall gluNurbsCurve(Gls::Opengltokens::PGLUNurbs nobj, int nknots, System::PSingle knot, int stride, System::PSingle ctlarray, int order, unsigned atype);
extern "C" void __stdcall gluNurbsSurface(Gls::Opengltokens::PGLUNurbs nobj, int sknot_count, System::PSingle sknot, int tknot_count, System::PSingle tknot, int s_stride, int t_stride, System::PSingle ctlarray, int sorder, int torder, unsigned atype);
extern "C" void __stdcall gluLoadSamplingMatrices(Gls::Opengltokens::PGLUNurbs nobj, const Gls::Vectortypes::TMatrix4f &modelMatrix, const Gls::Vectortypes::TMatrix4f &projMatrix, const Gls::Vectortypes::TVector4i &Viewport);
extern "C" void __stdcall gluNurbsProperty(Gls::Opengltokens::PGLUNurbs nobj, unsigned aproperty, float Value);
extern "C" void __stdcall gluGetNurbsProperty(Gls::Opengltokens::PGLUNurbs nobj, unsigned aproperty, System::PSingle Value);
extern "C" void __stdcall gluNurbsCallback(Gls::Opengltokens::PGLUNurbs nobj, unsigned which, Gls::Opengltokens::TGLUNurbsErrorProc fn);
extern "C" void __stdcall gluBeginPolygon(Gls::Opengltokens::PGLUTesselator tess);
extern "C" void __stdcall gluNextContour(Gls::Opengltokens::PGLUTesselator tess, unsigned atype);
extern "C" void __stdcall gluEndPolygon(Gls::Opengltokens::PGLUTesselator tess);
extern DELPHI_PACKAGE void * __fastcall GetProcAddressGLS(char * ProcName);
extern DELPHI_PACKAGE void * __fastcall GetProcAddressGLLib(char * ProcName);
extern DELPHI_PACKAGE void __fastcall TrimAndSplitVersionString(System::UnicodeString buffer, int &max, int &min);
extern DELPHI_PACKAGE bool __fastcall IsVersionMet(int MajorVersion, int MinorVersion, int actualMajorVersion, int actualMinorVersion);
extern DELPHI_PACKAGE bool __fastcall InitOpenGL(void);
extern DELPHI_PACKAGE bool __fastcall InitOpenGLFromLibrary(const System::UnicodeString GLName, const System::UnicodeString GLUName);
extern DELPHI_PACKAGE bool __fastcall IsOpenGLInitialized(void);
extern DELPHI_PACKAGE void __fastcall CloseOpenGL(void);
extern DELPHI_PACKAGE void __fastcall UnloadOpenGL(void);
extern DELPHI_PACKAGE bool __fastcall LoadOpenGL(void);
extern DELPHI_PACKAGE bool __fastcall LoadOpenGLFromLibrary(System::UnicodeString GLName, System::UnicodeString GLUName);
extern DELPHI_PACKAGE bool __fastcall IsOpenGLLoaded(void);
extern DELPHI_PACKAGE bool __fastcall IsMesaGL(void);
}	/* namespace Opengladapter */
}	/* namespace Gls */
#if !defined(DELPHIHEADER_NO_IMPLICIT_NAMESPACE_USE) && !defined(NO_USING_NAMESPACE_GLS_OPENGLADAPTER)
using namespace Gls::Opengladapter;
#endif
#if !defined(DELPHIHEADER_NO_IMPLICIT_NAMESPACE_USE) && !defined(NO_USING_NAMESPACE_GLS)
using namespace Gls;
#endif
#pragma pack(pop)
#pragma option pop

#pragma delphiheader end.
//-- end unit ----------------------------------------------------------------
#endif	// Gls_OpengladapterHPP
