// CodeGear C++Builder
// Copyright (c) 1995, 2022 by Embarcadero Technologies, Inc.
// All rights reserved

// (DO NOT EDIT: machine generated header) 'GLScene_DT.dpk' rev: 35.00 (Windows)

#ifndef Glscene_dtHPP
#define Glscene_dtHPP

#pragma delphiheader begin
#pragma option push
#pragma option -w-      // All warnings off
#pragma option -Vx      // Zero-length empty class member 
#pragma pack(push,8)
#include <System.hpp>	// (rtl)
#include <SysInit.hpp>
#include <FRColorEditor.hpp>
#include <FRTextureEdit.hpp>
#include <FmGuiLayoutEditor.hpp>
#include <FmGuiSkinEditor.hpp>
#include <FmShaderMemo.hpp>
#include <FmShaderUniformEditor.hpp>
#include <FmVectorEditor.hpp>
#include <FmSceneEditor.hpp>
#include <FmPlugInManagerEditor.hpp>
#include <FmXCollectionEditor.hpp>
#include <FmInfo.hpp>
#include <GLS.SceneRegister.hpp>
#include <GLS.XCollectionRegister.hpp>
#include <FRTrackBarEdit.hpp>
#include <FRFaceEditor.hpp>
#include <FRMaterialPreview.hpp>
#include <FmMaterialEditor.hpp>
#include <FmLibMaterialPicker.hpp>
#include <System.UITypes.hpp>	// (rtl)
#include <Winapi.Windows.hpp>	// (rtl)
#include <Winapi.PsAPI.hpp>	// (rtl)
#include <System.Character.hpp>	// (rtl)
#include <System.Internal.ExcUtils.hpp>	// (rtl)
#include <System.SysUtils.hpp>	// (rtl)
#include <System.VarUtils.hpp>	// (rtl)
#include <System.Variants.hpp>	// (rtl)
#include <System.TypInfo.hpp>	// (rtl)
#include <System.Math.hpp>	// (rtl)
#include <System.Generics.Defaults.hpp>	// (rtl)
#include <System.Rtti.hpp>	// (rtl)
#include <System.TimeSpan.hpp>	// (rtl)
#include <System.Classes.hpp>	// (rtl)
#include <System.Messaging.hpp>	// (rtl)
#include <System.Actions.hpp>	// (rtl)
#include <Winapi.ShellAPI.hpp>	// (rtl)
#include <System.DateUtils.hpp>	// (rtl)
#include <System.IOUtils.hpp>	// (rtl)
#include <System.IniFiles.hpp>	// (rtl)
#include <System.Win.Registry.hpp>	// (rtl)
#include <System.UIConsts.hpp>	// (rtl)
#include <Vcl.Graphics.hpp>	// (vcl)
#include <System.SyncObjs.hpp>	// (rtl)
#include <Winapi.UxTheme.hpp>	// (rtl)
#include <Vcl.ActnList.hpp>	// (vcl)
#include <System.AnsiStrings.hpp>	// (rtl)
#include <System.Win.ComObj.hpp>	// (rtl)
#include <Winapi.MsCTF.hpp>	// (rtl)
#include <Vcl.GraphUtil.hpp>	// (vcl)
#include <Vcl.Controls.hpp>	// (vcl)
#include <Vcl.StdCtrls.hpp>	// (vcl)
#include <Vcl.Clipbrd.hpp>	// (vcl)
#include <Vcl.Printers.hpp>	// (vcl)
#include <Vcl.ComCtrls.hpp>	// (vcl)
#include <System.HelpIntfs.hpp>	// (rtl)
#include <Vcl.Dialogs.hpp>	// (vcl)
#include <Vcl.ExtCtrls.hpp>	// (vcl)
#include <Vcl.Themes.hpp>	// (vcl)
#include <Vcl.Menus.hpp>	// (vcl)
#include <Winapi.FlatSB.hpp>	// (rtl)
#include <Vcl.Forms.hpp>	// (vcl)
#include <GLS.VectorGeometry.hpp>	// (GLScene_RT)
#include <Vcl.Buttons.hpp>	// (vcl)
#include <Vcl.ExtDlgs.hpp>	// (vcl)
#include <GLS.Utils.hpp>	// (GLScene_RT)
#include <GLS.PersistentClasses.hpp>	// (GLScene_RT)
#include <GLS.Color.hpp>	// (GLScene_RT)
#include <Winapi.OpenGL.hpp>	// (rtl)
#include <Vcl.Imaging.jpeg.hpp>	// (vclimg)
#include <Vcl.Imaging.pngimage.hpp>	// (vclimg)
#include <GLS.Logger.hpp>	// (GLScene_RT)
#include <GLS.OpenGLAdapter.hpp>	// (GLScene_RT)
#include <GLS.XOpenGL.hpp>	// (GLScene_RT)
#include <GLS.Context.hpp>	// (GLScene_RT)
#include <GLS.Graphics.hpp>	// (GLScene_RT)
#include <GLS.Coordinates.hpp>	// (GLScene_RT)
#include <GLS.XCollection.hpp>	// (GLScene_RT)
#include <GLS.VectorLists.hpp>	// (GLScene_RT)
#include <GLS.Material.hpp>	// (GLScene_RT)
#include <GLS.Scene.hpp>	// (GLScene_RT)
#include <GLS.Texture.hpp>	// (GLScene_RT)
#include <GLS.ProcTextures.hpp>	// (GLScene_RT)
#include <GLS.TextureImageEditors.hpp>	// (GLScene_RT)
#include <Vcl.Grids.hpp>	// (vcl)
#include <GLS.BitmapFont.hpp>	// (GLScene_RT)
#include <GLS.Objects.hpp>	// (GLScene_RT)
#include <GLS.HUDObjects.hpp>	// (GLScene_RT)
#include <GLS.WindowsFont.hpp>	// (GLScene_RT)
#include <GLS.Windows.hpp>	// (GLScene_RT)
#include <GLS.WindowsContext.hpp>	// (GLScene_RT)
#include <GLS.SceneViewer.hpp>	// (GLScene_RT)
#include <GLS.Memo.hpp>	// (GLScene_RT)
#include <GLSL.ShaderParameter.hpp>	// (GLScene_RT)
#include <IDEMessages.hpp>	// (designide)
#include <Vcl.CaptionedDockTree.hpp>	// (vcl)
#include <Vcl.DockTabSet.hpp>	// (vcl)
#include <Vcl.CategoryButtons.hpp>	// (vcl)
#include <Vcl.ButtonGroup.hpp>	// (vcl)
#include <Vcl.SysStyles.hpp>	// (vcl)
#include <Winapi.D2D1.hpp>	// (rtl)
#include <Vcl.Direct2D.hpp>	// (vcl)
#include <Vcl.Styles.hpp>	// (vcl)
#include <Vcl.ImageCollection.hpp>	// (vclwinx)
#include <BrandingAPI.hpp>	// (designide)
#include <Winapi.GDIPOBJ.hpp>	// (rtl)
#include <System.Devices.hpp>	// (rtl)
#include <Proxies.hpp>	// (designide)
#include <Vcl.AxCtrls.hpp>	// (vcl)
#include <Vcl.AppEvnts.hpp>	// (vcl)
#include <TreeIntf.hpp>	// (designide)
#include <TopLevels.hpp>	// (designide)
#include <StFilSys.hpp>	// (designide)
#include <IDEHelp.hpp>	// (designide)
#include <ComponentDesigner.hpp>	// (designide)
#include <PercentageDockTree.hpp>	// (designide)
#include <Vcl.WinXCtrls.hpp>	// (vclwinx)
#include <WaitDialog.hpp>	// (designide)
#include <Winapi.Mapi.hpp>	// (rtl)
#include <Vcl.ExtActns.hpp>	// (vcl)
#include <Vcl.ActnMenus.hpp>	// (vclactnband)
#include <Vcl.ActnMan.hpp>	// (vclactnband)
#include <Vcl.PlatformDefaultStyleActnCtrls.hpp>	// (vclactnband)
#include <BaseDock.hpp>	// (designide)
#include <DeskUtil.hpp>	// (designide)
#include <DeskForm.hpp>	// (designide)
#include <DockForm.hpp>	// (designide)
#include <Xml.Win.msxmldom.hpp>	// (xmlrtl)
#include <Xml.xmldom.hpp>	// (xmlrtl)
#include <ToolsAPI.hpp>	// (designide)
#include <DesignEditors.hpp>	// (designide)
#include <VCLEditors.hpp>	// (designide)
#include <GLS.ObjectManager.hpp>	// (GLScene_RT)
#include <GLS.Mesh.hpp>	// (GLScene_RT)
#include <GLS.MeshUtils.hpp>	// (GLScene_RT)
#include <GLS.VectorFileObjects.hpp>	// (GLScene_RT)
#include <GLS.GeomObjects.hpp>	// (GLScene_RT)
#include <GLS.ScriptBase.hpp>	// (GLScene_RT)
#include <GLS.AnimatedSprite.hpp>	// (GLScene_RT)
#include <GLS.HeightData.hpp>	// (GLScene_RT)
#include <GLS.AsyncHDS.hpp>	// (GLScene_RT)
#include <GLS.AsyncTimer.hpp>	// (GLScene_RT)
#include <GLS.Cadencer.hpp>	// (GLScene_RT)
#include <GLS.Atmosphere.hpp>	// (GLScene_RT)
#include <GLS.Blur.hpp>	// (GLScene_RT)
#include <GLS.BumpmapHDS.hpp>	// (GLScene_RT)
#include <GLS.Screen.hpp>	// (GLScene_RT)
#include <GLS.Navigator.hpp>	// (GLScene_RT)
#include <GLS.SmoothNavigator.hpp>	// (GLScene_RT)
#include <GLS.Manager.hpp>	// (GLScene_RT)
#include <GLS.Collision.hpp>	// (GLScene_RT)
#include <GLS.CompositeImage.hpp>	// (GLScene_RT)
#include <GLS.Console.hpp>	// (GLScene_RT)
#include <GLS.EllipseCollision.hpp>	// (GLScene_RT)
#include <GLS.MultiPolygon.hpp>	// (GLScene_RT)
#include <GLS.SpaceText.hpp>	// (GLScene_RT)
#include <GLS.Isolines.hpp>	// (GLScene_RT)
#include <GLS.ROAMPatch.hpp>	// (GLScene_RT)
#include <GLS.TerrainRenderer.hpp>	// (GLScene_RT)
#include <GLS.ProxyObjects.hpp>	// (GLScene_RT)
#include <GLS.MultiProxy.hpp>	// (GLScene_RT)
#include <GLS.DCE.hpp>	// (GLScene_RT)
#include <GLS.DynamicTexture.hpp>	// (GLScene_RT)
#include <GLS.ParticleFX.hpp>	// (GLScene_RT)
#include <GLS.ExplosionFx.hpp>	// (GLScene_RT)
#include <GLS.Extrusion.hpp>	// (GLScene_RT)
#include <GLS.MultiSampleImage.hpp>	// (GLScene_RT)
#include <GLS.FBORenderer.hpp>	// (GLScene_RT)
#include <GLS.Feedback.hpp>	// (GLScene_RT)
#include <GLS.FireFX.hpp>	// (GLScene_RT)
#include <GLS.FPSMovement.hpp>	// (GLScene_RT)
#include <GLS.GameMenu.hpp>	// (GLScene_RT)
#include <GLS.Graph.hpp>	// (GLScene_RT)
#include <GLS.HeightTileFileHDS.hpp>	// (GLScene_RT)
#include <GLS.Imposter.hpp>	// (GLScene_RT)
#include <GLS.LensFlare.hpp>	// (GLScene_RT)
#include <GLS.LinePFX.hpp>	// (GLScene_RT)
#include <GLS.TextureCombiners.hpp>	// (GLScene_RT)
#include <GLS.MaterialEx.hpp>	// (GLScene_RT)
#include <GLS.MaterialMultiProxy.hpp>	// (GLScene_RT)
#include <GLS.Mirror.hpp>	// (GLScene_RT)
#include <GLS.Particles.hpp>	// (GLScene_RT)
#include <GLS.Perlin.hpp>	// (GLScene_RT)
#include <GLS.PerlinPFX.hpp>	// (GLScene_RT)
#include <GLS.Portal.hpp>	// (GLScene_RT)
#include <GLS.ShadowHDS.hpp>	// (GLScene_RT)
#include <GLS.ShadowPlane.hpp>	// (GLScene_RT)
#include <GLS.ShadowVolume.hpp>	// (GLScene_RT)
#include <GLS.SceneForm.hpp>	// (GLScene_RT)
#include <GLS.SkyDome.hpp>	// (GLScene_RT)
#include <GLS.ArchiveManager.hpp>	// (GLScene_RT)
#include <GLS.Language.hpp>	// (GLScene_RT)
#include <GLSL.CustomShader.hpp>	// (GLScene_RT)
#include <GLSL.AsmShader.hpp>	// (GLScene_RT)
#include <GLSL.Shader.hpp>	// (GLScene_RT)
#include <GLSL.BumpShaders.hpp>	// (GLScene_RT)
#include <GLSL.ShaderCombiner.hpp>	// (GLScene_RT)
#include <GLSL.PhongShader.hpp>	// (GLScene_RT)
#include <GLSL.PostEffects.hpp>	// (GLScene_RT)
#include <GLSL.ProjectedTextures.hpp>	// (GLScene_RT)
#include <GLSL.DiffuseSpecularShader.hpp>	// (GLScene_RT)
#include <GLSL.TextureShaders.hpp>	// (GLScene_RT)
#include <GLS.ProjectedTextures.hpp>	// (GLScene_RT)
#include <GLS.TexLensFlare.hpp>	// (GLScene_RT)
#include <GLS.TexturedHDS.hpp>	// (GLScene_RT)
#include <GLS.ThorFX.hpp>	// (GLScene_RT)
#include <GLS.TilePlane.hpp>	// (GLScene_RT)
#include <GLS.Trail.hpp>	// (GLScene_RT)
#include <GLS.Tree.hpp>	// (GLScene_RT)
#include <GLS.WaterPlane.hpp>	// (GLScene_RT)
#include <GLS.zBuffer.hpp>	// (GLScene_RT)
#include <GLS.File3DSSceneObjects.hpp>	// (GLScene_RT)
#include <GLS.File3DS.hpp>	// (GLScene_RT)
#include <GLS.FileASE.hpp>	// (GLScene_RT)
#include <GLS.FileB3D.hpp>	// (GLScene_RT)
#include <GLS.FileGL2.hpp>	// (GLScene_RT)
#include <GLS.FileGLTF.hpp>	// (GLScene_RT)
#include <GLS.FileGTS.hpp>	// (GLScene_RT)
#include <GLS.FileLMTS.hpp>	// (GLScene_RT)
#include <Formats.LWO.hpp>	// (GLScene_RT)
#include <GLS.FileLWO.hpp>	// (GLScene_RT)
#include <GLS.FileMD2.hpp>	// (GLScene_RT)
#include <GLS.FileMD3.hpp>	// (GLScene_RT)
#include <GLS.FileMD5.hpp>	// (GLScene_RT)
#include <GLS.FileMDC.hpp>	// (GLScene_RT)
#include <GLS.FileMS3D.hpp>	// (GLScene_RT)
#include <GLS.FileNMF.hpp>	// (GLScene_RT)
#include <GLS.FileNurbs.hpp>	// (GLScene_RT)
#include <GLS.FileOBJ.hpp>	// (GLScene_RT)
#include <GLS.FileOCT.hpp>	// (GLScene_RT)
#include <GLS.FilePLY.hpp>	// (GLScene_RT)
#include <GLS.MeshBSP.hpp>	// (GLScene_RT)
#include <GLS.FileQ3BSP.hpp>	// (GLScene_RT)
#include <GLS.FileSMD.hpp>	// (GLScene_RT)
#include <GLS.FileSTL.hpp>	// (GLScene_RT)
#include <GLS.FileVRML.hpp>	// (GLScene_RT)
#include <GLS.SoundFileObjects.hpp>	// (GLScene_RT)
#include <GLS.FileWAV.hpp>	// (GLScene_RT)
#include <GLS.FileMP3.hpp>	// (GLScene_RT)
#include <GLS.FileDDS.hpp>	// (GLScene_RT)
#include <GLS.FileO3TC.hpp>	// (GLScene_RT)
#include <GLS.FileHDR.hpp>	// (GLScene_RT)
#include <GLS.FileJPEG.hpp>	// (GLScene_RT)
#include <GLS.FilePNG.hpp>	// (GLScene_RT)
#include <GLS.FileBMP.hpp>	// (GLScene_RT)
#include <GLS.FileTGA.hpp>	// (GLScene_RT)
#include <GLS.SoundManager.hpp>	// (GLScene_RT)
#include <GLS.Joystick.hpp>	// (GLScene_RT)
#include <GLS.ScreenSaver.hpp>	// (GLScene_RT)
#include <GLS.FullScreenViewer.hpp>	// (GLScene_RT)
#include <GLS.Behaviours.hpp>	// (GLScene_RT)
// PRG_EXT: .bpl
// BPI_DIR: ..\lib\Win32
// OBJ_DIR: ..\lib\Win32
// OBJ_EXT: .obj

//-- user supplied -----------------------------------------------------------

namespace Glscene_dt
{
//-- forward type declarations -----------------------------------------------
//-- type declarations -------------------------------------------------------
//-- var, const, procedure ---------------------------------------------------
}	/* namespace Glscene_dt */
#if !defined(DELPHIHEADER_NO_IMPLICIT_NAMESPACE_USE) && !defined(NO_USING_NAMESPACE_GLSCENE_DT)
using namespace Glscene_dt;
#endif
#pragma pack(pop)
#pragma option pop

#pragma delphiheader end.
//-- end unit ----------------------------------------------------------------
#endif	// Glscene_dtHPP
